// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BE.ConnectResponse.proto

package BE;

public final class BEConnectResponse {
  private BEConnectResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConnectResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string RouteName = 1;
    java.util.List<String> getRouteNameList();
    int getRouteNameCount();
    String getRouteName(int index);
  }
  public static final class ConnectResponse extends
      com.google.protobuf.GeneratedMessage
      implements ConnectResponseOrBuilder {
    // Use ConnectResponse.newBuilder() to construct.
    private ConnectResponse(Builder builder) {
      super(builder);
    }
    private ConnectResponse(boolean noInit) {}
    
    private static final ConnectResponse defaultInstance;
    public static ConnectResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEConnectResponse.internal_static_BE_ConnectResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEConnectResponse.internal_static_BE_ConnectResponse_fieldAccessorTable;
    }
    
    // repeated string RouteName = 1;
    public static final int ROUTENAME_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList routeName_;
    public java.util.List<String>
        getRouteNameList() {
      return routeName_;
    }
    public int getRouteNameCount() {
      return routeName_.size();
    }
    public String getRouteName(int index) {
      return routeName_.get(index);
    }
    
    private void initFields() {
      routeName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < routeName_.size(); i++) {
        output.writeBytes(1, routeName_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < routeName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(routeName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getRouteNameList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEConnectResponse.ConnectResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEConnectResponse.ConnectResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEConnectResponse.ConnectResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEConnectResponse.ConnectResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEConnectResponse.ConnectResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEConnectResponse.ConnectResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEConnectResponse.ConnectResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEConnectResponse.ConnectResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEConnectResponse.ConnectResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEConnectResponse.ConnectResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEConnectResponse.ConnectResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEConnectResponse.ConnectResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEConnectResponse.internal_static_BE_ConnectResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEConnectResponse.internal_static_BE_ConnectResponse_fieldAccessorTable;
      }
      
      // Construct using BE.BEConnectResponse.ConnectResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        routeName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEConnectResponse.ConnectResponse.getDescriptor();
      }
      
      public BE.BEConnectResponse.ConnectResponse getDefaultInstanceForType() {
        return BE.BEConnectResponse.ConnectResponse.getDefaultInstance();
      }
      
      public BE.BEConnectResponse.ConnectResponse build() {
        BE.BEConnectResponse.ConnectResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEConnectResponse.ConnectResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEConnectResponse.ConnectResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEConnectResponse.ConnectResponse buildPartial() {
        BE.BEConnectResponse.ConnectResponse result = new BE.BEConnectResponse.ConnectResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          routeName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              routeName_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.routeName_ = routeName_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEConnectResponse.ConnectResponse) {
          return mergeFrom((BE.BEConnectResponse.ConnectResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEConnectResponse.ConnectResponse other) {
        if (other == BE.BEConnectResponse.ConnectResponse.getDefaultInstance()) return this;
        if (!other.routeName_.isEmpty()) {
          if (routeName_.isEmpty()) {
            routeName_ = other.routeName_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRouteNameIsMutable();
            routeName_.addAll(other.routeName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureRouteNameIsMutable();
              routeName_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string RouteName = 1;
      private com.google.protobuf.LazyStringList routeName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRouteNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          routeName_ = new com.google.protobuf.LazyStringArrayList(routeName_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getRouteNameList() {
        return java.util.Collections.unmodifiableList(routeName_);
      }
      public int getRouteNameCount() {
        return routeName_.size();
      }
      public String getRouteName(int index) {
        return routeName_.get(index);
      }
      public Builder setRouteName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRouteNameIsMutable();
        routeName_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addRouteName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRouteNameIsMutable();
        routeName_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllRouteName(
          java.lang.Iterable<String> values) {
        ensureRouteNameIsMutable();
        super.addAll(values, routeName_);
        onChanged();
        return this;
      }
      public Builder clearRouteName() {
        routeName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addRouteName(com.google.protobuf.ByteString value) {
        ensureRouteNameIsMutable();
        routeName_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:BE.ConnectResponse)
    }
    
    static {
      defaultInstance = new ConnectResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.ConnectResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_ConnectResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_ConnectResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037protos/BE.ConnectResponse.proto\022\002BE\"$\n" +
      "\017ConnectResponse\022\021\n\tRouteName\030\001 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BE_ConnectResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BE_ConnectResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_ConnectResponse_descriptor,
              new java.lang.String[] { "RouteName", },
              BE.BEConnectResponse.ConnectResponse.class,
              BE.BEConnectResponse.ConnectResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
