// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BE.DataMarketCondition.proto

package BE;

public final class BEDataMarketCondition {
  private BEDataMarketCondition() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataMarketConditionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Ticker = 1;
    boolean hasTicker();
    String getTicker();
    
    // required .BE.DataMarketCondition.MarketStatus status = 2;
    boolean hasStatus();
    BE.BEDataMarketCondition.DataMarketCondition.MarketStatus getStatus();
  }
  public static final class DataMarketCondition extends
      com.google.protobuf.GeneratedMessage
      implements DataMarketConditionOrBuilder {
    // Use DataMarketCondition.newBuilder() to construct.
    private DataMarketCondition(Builder builder) {
      super(builder);
    }
    private DataMarketCondition(boolean noInit) {}
    
    private static final DataMarketCondition defaultInstance;
    public static DataMarketCondition getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataMarketCondition getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEDataMarketCondition.internal_static_BE_DataMarketCondition_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEDataMarketCondition.internal_static_BE_DataMarketCondition_fieldAccessorTable;
    }
    
    public enum MarketStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      OPEN(0, 0),
      CLOSE(1, 1),
      CALL(2, 2),
      ;
      
      public static final int OPEN_VALUE = 0;
      public static final int CLOSE_VALUE = 1;
      public static final int CALL_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static MarketStatus valueOf(int value) {
        switch (value) {
          case 0: return OPEN;
          case 1: return CLOSE;
          case 2: return CALL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MarketStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MarketStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MarketStatus>() {
              public MarketStatus findValueByNumber(int number) {
                return MarketStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BE.BEDataMarketCondition.DataMarketCondition.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MarketStatus[] VALUES = {
        OPEN, CLOSE, CALL, 
      };
      
      public static MarketStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MarketStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:BE.DataMarketCondition.MarketStatus)
    }
    
    private int bitField0_;
    // required string Ticker = 1;
    public static final int TICKER_FIELD_NUMBER = 1;
    private java.lang.Object ticker_;
    public boolean hasTicker() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTicker() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ticker_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTickerBytes() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ticker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .BE.DataMarketCondition.MarketStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private BE.BEDataMarketCondition.DataMarketCondition.MarketStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public BE.BEDataMarketCondition.DataMarketCondition.MarketStatus getStatus() {
      return status_;
    }
    
    private void initFields() {
      ticker_ = "";
      status_ = BE.BEDataMarketCondition.DataMarketCondition.MarketStatus.OPEN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTicker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTickerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTickerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataMarketCondition.DataMarketCondition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEDataMarketCondition.DataMarketCondition prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEDataMarketCondition.DataMarketConditionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEDataMarketCondition.internal_static_BE_DataMarketCondition_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEDataMarketCondition.internal_static_BE_DataMarketCondition_fieldAccessorTable;
      }
      
      // Construct using BE.BEDataMarketCondition.DataMarketCondition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ticker_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = BE.BEDataMarketCondition.DataMarketCondition.MarketStatus.OPEN;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEDataMarketCondition.DataMarketCondition.getDescriptor();
      }
      
      public BE.BEDataMarketCondition.DataMarketCondition getDefaultInstanceForType() {
        return BE.BEDataMarketCondition.DataMarketCondition.getDefaultInstance();
      }
      
      public BE.BEDataMarketCondition.DataMarketCondition build() {
        BE.BEDataMarketCondition.DataMarketCondition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEDataMarketCondition.DataMarketCondition buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEDataMarketCondition.DataMarketCondition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEDataMarketCondition.DataMarketCondition buildPartial() {
        BE.BEDataMarketCondition.DataMarketCondition result = new BE.BEDataMarketCondition.DataMarketCondition(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ticker_ = ticker_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEDataMarketCondition.DataMarketCondition) {
          return mergeFrom((BE.BEDataMarketCondition.DataMarketCondition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEDataMarketCondition.DataMarketCondition other) {
        if (other == BE.BEDataMarketCondition.DataMarketCondition.getDefaultInstance()) return this;
        if (other.hasTicker()) {
          setTicker(other.getTicker());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTicker()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ticker_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              BE.BEDataMarketCondition.DataMarketCondition.MarketStatus value = BE.BEDataMarketCondition.DataMarketCondition.MarketStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Ticker = 1;
      private java.lang.Object ticker_ = "";
      public boolean hasTicker() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTicker() {
        java.lang.Object ref = ticker_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ticker_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTicker(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ticker_ = value;
        onChanged();
        return this;
      }
      public Builder clearTicker() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ticker_ = getDefaultInstance().getTicker();
        onChanged();
        return this;
      }
      void setTicker(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        ticker_ = value;
        onChanged();
      }
      
      // required .BE.DataMarketCondition.MarketStatus status = 2;
      private BE.BEDataMarketCondition.DataMarketCondition.MarketStatus status_ = BE.BEDataMarketCondition.DataMarketCondition.MarketStatus.OPEN;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public BE.BEDataMarketCondition.DataMarketCondition.MarketStatus getStatus() {
        return status_;
      }
      public Builder setStatus(BE.BEDataMarketCondition.DataMarketCondition.MarketStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = BE.BEDataMarketCondition.DataMarketCondition.MarketStatus.OPEN;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BE.DataMarketCondition)
    }
    
    static {
      defaultInstance = new DataMarketCondition(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.DataMarketCondition)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_DataMarketCondition_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_DataMarketCondition_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#protos/BE.DataMarketCondition.proto\022\002B" +
      "E\"\212\001\n\023DataMarketCondition\022\016\n\006Ticker\030\001 \002(" +
      "\t\0224\n\006status\030\002 \002(\0162$.BE.DataMarketConditi" +
      "on.MarketStatus\"-\n\014MarketStatus\022\010\n\004OPEN\020" +
      "\000\022\t\n\005CLOSE\020\001\022\010\n\004CALL\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BE_DataMarketCondition_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BE_DataMarketCondition_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_DataMarketCondition_descriptor,
              new java.lang.String[] { "Ticker", "Status", },
              BE.BEDataMarketCondition.DataMarketCondition.class,
              BE.BEDataMarketCondition.DataMarketCondition.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
