// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BE.DataRequest.proto

package BE;

public final class BEDataRequest {
  private BEDataRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Ticker = 1;
    boolean hasTicker();
    String getTicker();
    
    // required .BE.DataRequest.EInformation information = 2;
    boolean hasInformation();
    BE.BEDataRequest.DataRequest.EInformation getInformation();
    
    // optional int32 depth = 3 [default = 5];
    boolean hasDepth();
    int getDepth();
  }
  public static final class DataRequest extends
      com.google.protobuf.GeneratedMessage
      implements DataRequestOrBuilder {
    // Use DataRequest.newBuilder() to construct.
    private DataRequest(Builder builder) {
      super(builder);
    }
    private DataRequest(boolean noInit) {}
    
    private static final DataRequest defaultInstance;
    public static DataRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEDataRequest.internal_static_BE_DataRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEDataRequest.internal_static_BE_DataRequest_fieldAccessorTable;
    }
    
    public enum EInformation
        implements com.google.protobuf.ProtocolMessageEnum {
      TRADE(0, 0),
      BOOK(1, 1),
      MARKET_STATUS(2, 2),
      ;
      
      public static final int TRADE_VALUE = 0;
      public static final int BOOK_VALUE = 1;
      public static final int MARKET_STATUS_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static EInformation valueOf(int value) {
        switch (value) {
          case 0: return TRADE;
          case 1: return BOOK;
          case 2: return MARKET_STATUS;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<EInformation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EInformation>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EInformation>() {
              public EInformation findValueByNumber(int number) {
                return EInformation.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BE.BEDataRequest.DataRequest.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final EInformation[] VALUES = {
        TRADE, BOOK, MARKET_STATUS, 
      };
      
      public static EInformation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private EInformation(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:BE.DataRequest.EInformation)
    }
    
    private int bitField0_;
    // required string Ticker = 1;
    public static final int TICKER_FIELD_NUMBER = 1;
    private java.lang.Object ticker_;
    public boolean hasTicker() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTicker() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ticker_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTickerBytes() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ticker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .BE.DataRequest.EInformation information = 2;
    public static final int INFORMATION_FIELD_NUMBER = 2;
    private BE.BEDataRequest.DataRequest.EInformation information_;
    public boolean hasInformation() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public BE.BEDataRequest.DataRequest.EInformation getInformation() {
      return information_;
    }
    
    // optional int32 depth = 3 [default = 5];
    public static final int DEPTH_FIELD_NUMBER = 3;
    private int depth_;
    public boolean hasDepth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDepth() {
      return depth_;
    }
    
    private void initFields() {
      ticker_ = "";
      information_ = BE.BEDataRequest.DataRequest.EInformation.TRADE;
      depth_ = 5;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTicker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInformation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTickerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, information_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, depth_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTickerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, information_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, depth_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEDataRequest.DataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataRequest.DataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataRequest.DataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataRequest.DataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataRequest.DataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataRequest.DataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataRequest.DataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataRequest.DataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataRequest.DataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataRequest.DataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEDataRequest.DataRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEDataRequest.DataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEDataRequest.internal_static_BE_DataRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEDataRequest.internal_static_BE_DataRequest_fieldAccessorTable;
      }
      
      // Construct using BE.BEDataRequest.DataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ticker_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        information_ = BE.BEDataRequest.DataRequest.EInformation.TRADE;
        bitField0_ = (bitField0_ & ~0x00000002);
        depth_ = 5;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEDataRequest.DataRequest.getDescriptor();
      }
      
      public BE.BEDataRequest.DataRequest getDefaultInstanceForType() {
        return BE.BEDataRequest.DataRequest.getDefaultInstance();
      }
      
      public BE.BEDataRequest.DataRequest build() {
        BE.BEDataRequest.DataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEDataRequest.DataRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEDataRequest.DataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEDataRequest.DataRequest buildPartial() {
        BE.BEDataRequest.DataRequest result = new BE.BEDataRequest.DataRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ticker_ = ticker_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.information_ = information_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.depth_ = depth_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEDataRequest.DataRequest) {
          return mergeFrom((BE.BEDataRequest.DataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEDataRequest.DataRequest other) {
        if (other == BE.BEDataRequest.DataRequest.getDefaultInstance()) return this;
        if (other.hasTicker()) {
          setTicker(other.getTicker());
        }
        if (other.hasInformation()) {
          setInformation(other.getInformation());
        }
        if (other.hasDepth()) {
          setDepth(other.getDepth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTicker()) {
          
          return false;
        }
        if (!hasInformation()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ticker_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              BE.BEDataRequest.DataRequest.EInformation value = BE.BEDataRequest.DataRequest.EInformation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                information_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              depth_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Ticker = 1;
      private java.lang.Object ticker_ = "";
      public boolean hasTicker() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTicker() {
        java.lang.Object ref = ticker_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ticker_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTicker(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ticker_ = value;
        onChanged();
        return this;
      }
      public Builder clearTicker() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ticker_ = getDefaultInstance().getTicker();
        onChanged();
        return this;
      }
      void setTicker(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        ticker_ = value;
        onChanged();
      }
      
      // required .BE.DataRequest.EInformation information = 2;
      private BE.BEDataRequest.DataRequest.EInformation information_ = BE.BEDataRequest.DataRequest.EInformation.TRADE;
      public boolean hasInformation() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public BE.BEDataRequest.DataRequest.EInformation getInformation() {
        return information_;
      }
      public Builder setInformation(BE.BEDataRequest.DataRequest.EInformation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        information_ = value;
        onChanged();
        return this;
      }
      public Builder clearInformation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        information_ = BE.BEDataRequest.DataRequest.EInformation.TRADE;
        onChanged();
        return this;
      }
      
      // optional int32 depth = 3 [default = 5];
      private int depth_ = 5;
      public boolean hasDepth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDepth() {
        return depth_;
      }
      public Builder setDepth(int value) {
        bitField0_ |= 0x00000004;
        depth_ = value;
        onChanged();
        return this;
      }
      public Builder clearDepth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        depth_ = 5;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BE.DataRequest)
    }
    
    static {
      defaultInstance = new DataRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.DataRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_DataRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_DataRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protos/BE.DataRequest.proto\022\002BE\"\232\001\n\013Da" +
      "taRequest\022\016\n\006Ticker\030\001 \002(\t\0221\n\013information" +
      "\030\002 \002(\0162\034.BE.DataRequest.EInformation\022\020\n\005" +
      "depth\030\003 \001(\005:\0015\"6\n\014EInformation\022\t\n\005TRADE\020" +
      "\000\022\010\n\004BOOK\020\001\022\021\n\rMARKET_STATUS\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BE_DataRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BE_DataRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_DataRequest_descriptor,
              new java.lang.String[] { "Ticker", "Information", "Depth", },
              BE.BEDataRequest.DataRequest.class,
              BE.BEDataRequest.DataRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
