// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BE.DataBook.proto

package BE;

public final class BEDataBook {
  private BEDataBook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataBookEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 TimeStamp = 1;
    boolean hasTimeStamp();
    long getTimeStamp();
    
    // required double Quantity = 2;
    boolean hasQuantity();
    double getQuantity();
    
    // required double Price = 3;
    boolean hasPrice();
    double getPrice();
    
    // required string IdBroker = 4;
    boolean hasIdBroker();
    String getIdBroker();
    
    // required int64 Position = 5;
    boolean hasPosition();
    long getPosition();
    
    // optional .BE.DataBookEntry.EQuoteCondition QuoteCondition = 6 [default = REGULAR];
    boolean hasQuoteCondition();
    BE.BEDataBook.DataBookEntry.EQuoteCondition getQuoteCondition();
  }
  public static final class DataBookEntry extends
      com.google.protobuf.GeneratedMessage
      implements DataBookEntryOrBuilder {
    // Use DataBookEntry.newBuilder() to construct.
    private DataBookEntry(Builder builder) {
      super(builder);
    }
    private DataBookEntry(boolean noInit) {}
    
    private static final DataBookEntry defaultInstance;
    public static DataBookEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataBookEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEDataBook.internal_static_BE_DataBookEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEDataBook.internal_static_BE_DataBookEntry_fieldAccessorTable;
    }
    
    public enum EQuoteCondition
        implements com.google.protobuf.ProtocolMessageEnum {
      REGULAR(0, 1),
      BIDASKAUTOEXEC(1, 2),
      ROTATION(2, 3),
      SPECIALISTASK(3, 4),
      SPECIALISTBID(4, 5),
      LOCKED(5, 6),
      FASTMARKET(6, 7),
      SPECIALISTBIDASK(7, 8),
      ONESIDE(8, 9),
      OPENINGQUOTE(9, 10),
      CLOSINGQUOTE(10, 11),
      MARKETMAKERCLOSED(11, 12),
      DEPTHONASK(12, 13),
      DEPTHONBID(13, 14),
      DEPTHONBIDASK(14, 15),
      TIER3(15, 16),
      CROSSED(16, 17),
      HALTED(17, 18),
      OPERATIONALHALT(18, 19),
      NEWSOUT(19, 20),
      NEWSPENDING(20, 21),
      NONFIRM(21, 22),
      DUETORELATED(22, 23),
      RESUME(23, 24),
      NOMARKETMAKERS(24, 25),
      ORDERIMBALANCE(25, 26),
      ORDERINFLUX(26, 27),
      INDICATED(27, 28),
      PREOPEN(28, 29),
      INVIEWOFCOMMON(29, 30),
      RELATEDNEWSPENDING(30, 31),
      RELATEDNEWSOUT(31, 32),
      ADDITIONALINFO(32, 33),
      RELATEDADDLINFO(33, 34),
      NOOPENRESUME(34, 35),
      DELETED(35, 36),
      REGULATORYHALT(36, 37),
      SECSUSPENSION(37, 38),
      NONCOMLIANCE(38, 39),
      FILINGSNOTCURRENT(39, 40),
      CATS_HALTED(40, 41),
      CATS(41, 42),
      EXDIVORSPLIT(42, 43),
      UNASSIGNED(43, 44),
      INSIDEOPEN(44, 45),
      INSIDECLOSED(45, 46),
      OFFERWANTED(46, 47),
      BIDWANTED(47, 48),
      CASH(48, 49),
      INACTIVE(49, 50),
      NATIONALBBO(50, 51),
      NOMINAL(51, 52),
      CABINET(52, 53),
      NOMINALCABINET(53, 54),
      BLANKPRICE(54, 55),
      SLOWBIDASK(55, 56),
      SLOWLIST(56, 57),
      SLOWBID(57, 58),
      SLOWASK(58, 59),
      BIDOFFERWANTED(59, 60),
      SUBPENNY(60, 61),
      NONBBO(61, 62),
      ;
      
      public static final int REGULAR_VALUE = 1;
      public static final int BIDASKAUTOEXEC_VALUE = 2;
      public static final int ROTATION_VALUE = 3;
      public static final int SPECIALISTASK_VALUE = 4;
      public static final int SPECIALISTBID_VALUE = 5;
      public static final int LOCKED_VALUE = 6;
      public static final int FASTMARKET_VALUE = 7;
      public static final int SPECIALISTBIDASK_VALUE = 8;
      public static final int ONESIDE_VALUE = 9;
      public static final int OPENINGQUOTE_VALUE = 10;
      public static final int CLOSINGQUOTE_VALUE = 11;
      public static final int MARKETMAKERCLOSED_VALUE = 12;
      public static final int DEPTHONASK_VALUE = 13;
      public static final int DEPTHONBID_VALUE = 14;
      public static final int DEPTHONBIDASK_VALUE = 15;
      public static final int TIER3_VALUE = 16;
      public static final int CROSSED_VALUE = 17;
      public static final int HALTED_VALUE = 18;
      public static final int OPERATIONALHALT_VALUE = 19;
      public static final int NEWSOUT_VALUE = 20;
      public static final int NEWSPENDING_VALUE = 21;
      public static final int NONFIRM_VALUE = 22;
      public static final int DUETORELATED_VALUE = 23;
      public static final int RESUME_VALUE = 24;
      public static final int NOMARKETMAKERS_VALUE = 25;
      public static final int ORDERIMBALANCE_VALUE = 26;
      public static final int ORDERINFLUX_VALUE = 27;
      public static final int INDICATED_VALUE = 28;
      public static final int PREOPEN_VALUE = 29;
      public static final int INVIEWOFCOMMON_VALUE = 30;
      public static final int RELATEDNEWSPENDING_VALUE = 31;
      public static final int RELATEDNEWSOUT_VALUE = 32;
      public static final int ADDITIONALINFO_VALUE = 33;
      public static final int RELATEDADDLINFO_VALUE = 34;
      public static final int NOOPENRESUME_VALUE = 35;
      public static final int DELETED_VALUE = 36;
      public static final int REGULATORYHALT_VALUE = 37;
      public static final int SECSUSPENSION_VALUE = 38;
      public static final int NONCOMLIANCE_VALUE = 39;
      public static final int FILINGSNOTCURRENT_VALUE = 40;
      public static final int CATS_HALTED_VALUE = 41;
      public static final int CATS_VALUE = 42;
      public static final int EXDIVORSPLIT_VALUE = 43;
      public static final int UNASSIGNED_VALUE = 44;
      public static final int INSIDEOPEN_VALUE = 45;
      public static final int INSIDECLOSED_VALUE = 46;
      public static final int OFFERWANTED_VALUE = 47;
      public static final int BIDWANTED_VALUE = 48;
      public static final int CASH_VALUE = 49;
      public static final int INACTIVE_VALUE = 50;
      public static final int NATIONALBBO_VALUE = 51;
      public static final int NOMINAL_VALUE = 52;
      public static final int CABINET_VALUE = 53;
      public static final int NOMINALCABINET_VALUE = 54;
      public static final int BLANKPRICE_VALUE = 55;
      public static final int SLOWBIDASK_VALUE = 56;
      public static final int SLOWLIST_VALUE = 57;
      public static final int SLOWBID_VALUE = 58;
      public static final int SLOWASK_VALUE = 59;
      public static final int BIDOFFERWANTED_VALUE = 60;
      public static final int SUBPENNY_VALUE = 61;
      public static final int NONBBO_VALUE = 62;
      
      
      public final int getNumber() { return value; }
      
      public static EQuoteCondition valueOf(int value) {
        switch (value) {
          case 1: return REGULAR;
          case 2: return BIDASKAUTOEXEC;
          case 3: return ROTATION;
          case 4: return SPECIALISTASK;
          case 5: return SPECIALISTBID;
          case 6: return LOCKED;
          case 7: return FASTMARKET;
          case 8: return SPECIALISTBIDASK;
          case 9: return ONESIDE;
          case 10: return OPENINGQUOTE;
          case 11: return CLOSINGQUOTE;
          case 12: return MARKETMAKERCLOSED;
          case 13: return DEPTHONASK;
          case 14: return DEPTHONBID;
          case 15: return DEPTHONBIDASK;
          case 16: return TIER3;
          case 17: return CROSSED;
          case 18: return HALTED;
          case 19: return OPERATIONALHALT;
          case 20: return NEWSOUT;
          case 21: return NEWSPENDING;
          case 22: return NONFIRM;
          case 23: return DUETORELATED;
          case 24: return RESUME;
          case 25: return NOMARKETMAKERS;
          case 26: return ORDERIMBALANCE;
          case 27: return ORDERINFLUX;
          case 28: return INDICATED;
          case 29: return PREOPEN;
          case 30: return INVIEWOFCOMMON;
          case 31: return RELATEDNEWSPENDING;
          case 32: return RELATEDNEWSOUT;
          case 33: return ADDITIONALINFO;
          case 34: return RELATEDADDLINFO;
          case 35: return NOOPENRESUME;
          case 36: return DELETED;
          case 37: return REGULATORYHALT;
          case 38: return SECSUSPENSION;
          case 39: return NONCOMLIANCE;
          case 40: return FILINGSNOTCURRENT;
          case 41: return CATS_HALTED;
          case 42: return CATS;
          case 43: return EXDIVORSPLIT;
          case 44: return UNASSIGNED;
          case 45: return INSIDEOPEN;
          case 46: return INSIDECLOSED;
          case 47: return OFFERWANTED;
          case 48: return BIDWANTED;
          case 49: return CASH;
          case 50: return INACTIVE;
          case 51: return NATIONALBBO;
          case 52: return NOMINAL;
          case 53: return CABINET;
          case 54: return NOMINALCABINET;
          case 55: return BLANKPRICE;
          case 56: return SLOWBIDASK;
          case 57: return SLOWLIST;
          case 58: return SLOWBID;
          case 59: return SLOWASK;
          case 60: return BIDOFFERWANTED;
          case 61: return SUBPENNY;
          case 62: return NONBBO;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<EQuoteCondition>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EQuoteCondition>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EQuoteCondition>() {
              public EQuoteCondition findValueByNumber(int number) {
                return EQuoteCondition.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BE.BEDataBook.DataBookEntry.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final EQuoteCondition[] VALUES = {
        REGULAR, BIDASKAUTOEXEC, ROTATION, SPECIALISTASK, SPECIALISTBID, LOCKED, FASTMARKET, SPECIALISTBIDASK, ONESIDE, OPENINGQUOTE, CLOSINGQUOTE, MARKETMAKERCLOSED, DEPTHONASK, DEPTHONBID, DEPTHONBIDASK, TIER3, CROSSED, HALTED, OPERATIONALHALT, NEWSOUT, NEWSPENDING, NONFIRM, DUETORELATED, RESUME, NOMARKETMAKERS, ORDERIMBALANCE, ORDERINFLUX, INDICATED, PREOPEN, INVIEWOFCOMMON, RELATEDNEWSPENDING, RELATEDNEWSOUT, ADDITIONALINFO, RELATEDADDLINFO, NOOPENRESUME, DELETED, REGULATORYHALT, SECSUSPENSION, NONCOMLIANCE, FILINGSNOTCURRENT, CATS_HALTED, CATS, EXDIVORSPLIT, UNASSIGNED, INSIDEOPEN, INSIDECLOSED, OFFERWANTED, BIDWANTED, CASH, INACTIVE, NATIONALBBO, NOMINAL, CABINET, NOMINALCABINET, BLANKPRICE, SLOWBIDASK, SLOWLIST, SLOWBID, SLOWASK, BIDOFFERWANTED, SUBPENNY, NONBBO, 
      };
      
      public static EQuoteCondition valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private EQuoteCondition(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:BE.DataBookEntry.EQuoteCondition)
    }
    
    private int bitField0_;
    // required int64 TimeStamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timeStamp_;
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimeStamp() {
      return timeStamp_;
    }
    
    // required double Quantity = 2;
    public static final int QUANTITY_FIELD_NUMBER = 2;
    private double quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getQuantity() {
      return quantity_;
    }
    
    // required double Price = 3;
    public static final int PRICE_FIELD_NUMBER = 3;
    private double price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getPrice() {
      return price_;
    }
    
    // required string IdBroker = 4;
    public static final int IDBROKER_FIELD_NUMBER = 4;
    private java.lang.Object idBroker_;
    public boolean hasIdBroker() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getIdBroker() {
      java.lang.Object ref = idBroker_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          idBroker_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBrokerBytes() {
      java.lang.Object ref = idBroker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        idBroker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 Position = 5;
    public static final int POSITION_FIELD_NUMBER = 5;
    private long position_;
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getPosition() {
      return position_;
    }
    
    // optional .BE.DataBookEntry.EQuoteCondition QuoteCondition = 6 [default = REGULAR];
    public static final int QUOTECONDITION_FIELD_NUMBER = 6;
    private BE.BEDataBook.DataBookEntry.EQuoteCondition quoteCondition_;
    public boolean hasQuoteCondition() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public BE.BEDataBook.DataBookEntry.EQuoteCondition getQuoteCondition() {
      return quoteCondition_;
    }
    
    private void initFields() {
      timeStamp_ = 0L;
      quantity_ = 0D;
      price_ = 0D;
      idBroker_ = "";
      position_ = 0L;
      quoteCondition_ = BE.BEDataBook.DataBookEntry.EQuoteCondition.REGULAR;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdBroker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, quantity_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIdBrokerBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, position_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, quoteCondition_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, quantity_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIdBrokerBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, position_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, quoteCondition_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEDataBook.DataBookEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataBook.DataBookEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataBook.DataBookEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataBook.DataBookEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataBook.DataBookEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataBook.DataBookEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataBook.DataBookEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataBook.DataBookEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataBook.DataBookEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataBook.DataBookEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEDataBook.DataBookEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEDataBook.DataBookEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEDataBook.internal_static_BE_DataBookEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEDataBook.internal_static_BE_DataBookEntry_fieldAccessorTable;
      }
      
      // Construct using BE.BEDataBook.DataBookEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        quantity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        idBroker_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        position_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        quoteCondition_ = BE.BEDataBook.DataBookEntry.EQuoteCondition.REGULAR;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEDataBook.DataBookEntry.getDescriptor();
      }
      
      public BE.BEDataBook.DataBookEntry getDefaultInstanceForType() {
        return BE.BEDataBook.DataBookEntry.getDefaultInstance();
      }
      
      public BE.BEDataBook.DataBookEntry build() {
        BE.BEDataBook.DataBookEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEDataBook.DataBookEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEDataBook.DataBookEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEDataBook.DataBookEntry buildPartial() {
        BE.BEDataBook.DataBookEntry result = new BE.BEDataBook.DataBookEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.idBroker_ = idBroker_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.position_ = position_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.quoteCondition_ = quoteCondition_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEDataBook.DataBookEntry) {
          return mergeFrom((BE.BEDataBook.DataBookEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEDataBook.DataBookEntry other) {
        if (other == BE.BEDataBook.DataBookEntry.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasIdBroker()) {
          setIdBroker(other.getIdBroker());
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        if (other.hasQuoteCondition()) {
          setQuoteCondition(other.getQuoteCondition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimeStamp()) {
          
          return false;
        }
        if (!hasQuantity()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        if (!hasIdBroker()) {
          
          return false;
        }
        if (!hasPosition()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timeStamp_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              quantity_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              price_ = input.readDouble();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              idBroker_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              position_ = input.readInt64();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              BE.BEDataBook.DataBookEntry.EQuoteCondition value = BE.BEDataBook.DataBookEntry.EQuoteCondition.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                quoteCondition_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 TimeStamp = 1;
      private long timeStamp_ ;
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimeStamp() {
        return timeStamp_;
      }
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required double Quantity = 2;
      private double quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(double value) {
        bitField0_ |= 0x00000002;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0D;
        onChanged();
        return this;
      }
      
      // required double Price = 3;
      private double price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getPrice() {
        return price_;
      }
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0D;
        onChanged();
        return this;
      }
      
      // required string IdBroker = 4;
      private java.lang.Object idBroker_ = "";
      public boolean hasIdBroker() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getIdBroker() {
        java.lang.Object ref = idBroker_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          idBroker_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIdBroker(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        idBroker_ = value;
        onChanged();
        return this;
      }
      public Builder clearIdBroker() {
        bitField0_ = (bitField0_ & ~0x00000008);
        idBroker_ = getDefaultInstance().getIdBroker();
        onChanged();
        return this;
      }
      void setIdBroker(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        idBroker_ = value;
        onChanged();
      }
      
      // required int64 Position = 5;
      private long position_ ;
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getPosition() {
        return position_;
      }
      public Builder setPosition(long value) {
        bitField0_ |= 0x00000010;
        position_ = value;
        onChanged();
        return this;
      }
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000010);
        position_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .BE.DataBookEntry.EQuoteCondition QuoteCondition = 6 [default = REGULAR];
      private BE.BEDataBook.DataBookEntry.EQuoteCondition quoteCondition_ = BE.BEDataBook.DataBookEntry.EQuoteCondition.REGULAR;
      public boolean hasQuoteCondition() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public BE.BEDataBook.DataBookEntry.EQuoteCondition getQuoteCondition() {
        return quoteCondition_;
      }
      public Builder setQuoteCondition(BE.BEDataBook.DataBookEntry.EQuoteCondition value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        quoteCondition_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuoteCondition() {
        bitField0_ = (bitField0_ & ~0x00000020);
        quoteCondition_ = BE.BEDataBook.DataBookEntry.EQuoteCondition.REGULAR;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BE.DataBookEntry)
    }
    
    static {
      defaultInstance = new DataBookEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.DataBookEntry)
  }
  
  public interface DataBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string Ticker = 1;
    boolean hasTicker();
    String getTicker();
    
    // repeated .BE.DataBookEntry AskBook = 2;
    java.util.List<BE.BEDataBook.DataBookEntry> 
        getAskBookList();
    BE.BEDataBook.DataBookEntry getAskBook(int index);
    int getAskBookCount();
    java.util.List<? extends BE.BEDataBook.DataBookEntryOrBuilder> 
        getAskBookOrBuilderList();
    BE.BEDataBook.DataBookEntryOrBuilder getAskBookOrBuilder(
        int index);
    
    // repeated .BE.DataBookEntry BidBook = 3;
    java.util.List<BE.BEDataBook.DataBookEntry> 
        getBidBookList();
    BE.BEDataBook.DataBookEntry getBidBook(int index);
    int getBidBookCount();
    java.util.List<? extends BE.BEDataBook.DataBookEntryOrBuilder> 
        getBidBookOrBuilderList();
    BE.BEDataBook.DataBookEntryOrBuilder getBidBookOrBuilder(
        int index);
  }
  public static final class DataBook extends
      com.google.protobuf.GeneratedMessage
      implements DataBookOrBuilder {
    // Use DataBook.newBuilder() to construct.
    private DataBook(Builder builder) {
      super(builder);
    }
    private DataBook(boolean noInit) {}
    
    private static final DataBook defaultInstance;
    public static DataBook getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataBook getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEDataBook.internal_static_BE_DataBook_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEDataBook.internal_static_BE_DataBook_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string Ticker = 1;
    public static final int TICKER_FIELD_NUMBER = 1;
    private java.lang.Object ticker_;
    public boolean hasTicker() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTicker() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ticker_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTickerBytes() {
      java.lang.Object ref = ticker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ticker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .BE.DataBookEntry AskBook = 2;
    public static final int ASKBOOK_FIELD_NUMBER = 2;
    private java.util.List<BE.BEDataBook.DataBookEntry> askBook_;
    public java.util.List<BE.BEDataBook.DataBookEntry> getAskBookList() {
      return askBook_;
    }
    public java.util.List<? extends BE.BEDataBook.DataBookEntryOrBuilder> 
        getAskBookOrBuilderList() {
      return askBook_;
    }
    public int getAskBookCount() {
      return askBook_.size();
    }
    public BE.BEDataBook.DataBookEntry getAskBook(int index) {
      return askBook_.get(index);
    }
    public BE.BEDataBook.DataBookEntryOrBuilder getAskBookOrBuilder(
        int index) {
      return askBook_.get(index);
    }
    
    // repeated .BE.DataBookEntry BidBook = 3;
    public static final int BIDBOOK_FIELD_NUMBER = 3;
    private java.util.List<BE.BEDataBook.DataBookEntry> bidBook_;
    public java.util.List<BE.BEDataBook.DataBookEntry> getBidBookList() {
      return bidBook_;
    }
    public java.util.List<? extends BE.BEDataBook.DataBookEntryOrBuilder> 
        getBidBookOrBuilderList() {
      return bidBook_;
    }
    public int getBidBookCount() {
      return bidBook_.size();
    }
    public BE.BEDataBook.DataBookEntry getBidBook(int index) {
      return bidBook_.get(index);
    }
    public BE.BEDataBook.DataBookEntryOrBuilder getBidBookOrBuilder(
        int index) {
      return bidBook_.get(index);
    }
    
    private void initFields() {
      ticker_ = "";
      askBook_ = java.util.Collections.emptyList();
      bidBook_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTicker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAskBookCount(); i++) {
        if (!getAskBook(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getBidBookCount(); i++) {
        if (!getBidBook(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTickerBytes());
      }
      for (int i = 0; i < askBook_.size(); i++) {
        output.writeMessage(2, askBook_.get(i));
      }
      for (int i = 0; i < bidBook_.size(); i++) {
        output.writeMessage(3, bidBook_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTickerBytes());
      }
      for (int i = 0; i < askBook_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, askBook_.get(i));
      }
      for (int i = 0; i < bidBook_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, bidBook_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEDataBook.DataBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataBook.DataBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataBook.DataBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEDataBook.DataBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataBook.DataBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataBook.DataBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEDataBook.DataBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataBook.DataBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEDataBook.DataBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEDataBook.DataBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEDataBook.DataBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEDataBook.DataBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEDataBook.internal_static_BE_DataBook_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEDataBook.internal_static_BE_DataBook_fieldAccessorTable;
      }
      
      // Construct using BE.BEDataBook.DataBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAskBookFieldBuilder();
          getBidBookFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ticker_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (askBookBuilder_ == null) {
          askBook_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          askBookBuilder_.clear();
        }
        if (bidBookBuilder_ == null) {
          bidBook_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          bidBookBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEDataBook.DataBook.getDescriptor();
      }
      
      public BE.BEDataBook.DataBook getDefaultInstanceForType() {
        return BE.BEDataBook.DataBook.getDefaultInstance();
      }
      
      public BE.BEDataBook.DataBook build() {
        BE.BEDataBook.DataBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEDataBook.DataBook buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEDataBook.DataBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEDataBook.DataBook buildPartial() {
        BE.BEDataBook.DataBook result = new BE.BEDataBook.DataBook(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ticker_ = ticker_;
        if (askBookBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            askBook_ = java.util.Collections.unmodifiableList(askBook_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.askBook_ = askBook_;
        } else {
          result.askBook_ = askBookBuilder_.build();
        }
        if (bidBookBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            bidBook_ = java.util.Collections.unmodifiableList(bidBook_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.bidBook_ = bidBook_;
        } else {
          result.bidBook_ = bidBookBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEDataBook.DataBook) {
          return mergeFrom((BE.BEDataBook.DataBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEDataBook.DataBook other) {
        if (other == BE.BEDataBook.DataBook.getDefaultInstance()) return this;
        if (other.hasTicker()) {
          setTicker(other.getTicker());
        }
        if (askBookBuilder_ == null) {
          if (!other.askBook_.isEmpty()) {
            if (askBook_.isEmpty()) {
              askBook_ = other.askBook_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAskBookIsMutable();
              askBook_.addAll(other.askBook_);
            }
            onChanged();
          }
        } else {
          if (!other.askBook_.isEmpty()) {
            if (askBookBuilder_.isEmpty()) {
              askBookBuilder_.dispose();
              askBookBuilder_ = null;
              askBook_ = other.askBook_;
              bitField0_ = (bitField0_ & ~0x00000002);
              askBookBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAskBookFieldBuilder() : null;
            } else {
              askBookBuilder_.addAllMessages(other.askBook_);
            }
          }
        }
        if (bidBookBuilder_ == null) {
          if (!other.bidBook_.isEmpty()) {
            if (bidBook_.isEmpty()) {
              bidBook_ = other.bidBook_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBidBookIsMutable();
              bidBook_.addAll(other.bidBook_);
            }
            onChanged();
          }
        } else {
          if (!other.bidBook_.isEmpty()) {
            if (bidBookBuilder_.isEmpty()) {
              bidBookBuilder_.dispose();
              bidBookBuilder_ = null;
              bidBook_ = other.bidBook_;
              bitField0_ = (bitField0_ & ~0x00000004);
              bidBookBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBidBookFieldBuilder() : null;
            } else {
              bidBookBuilder_.addAllMessages(other.bidBook_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTicker()) {
          
          return false;
        }
        for (int i = 0; i < getAskBookCount(); i++) {
          if (!getAskBook(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getBidBookCount(); i++) {
          if (!getBidBook(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ticker_ = input.readBytes();
              break;
            }
            case 18: {
              BE.BEDataBook.DataBookEntry.Builder subBuilder = BE.BEDataBook.DataBookEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAskBook(subBuilder.buildPartial());
              break;
            }
            case 26: {
              BE.BEDataBook.DataBookEntry.Builder subBuilder = BE.BEDataBook.DataBookEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBidBook(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string Ticker = 1;
      private java.lang.Object ticker_ = "";
      public boolean hasTicker() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTicker() {
        java.lang.Object ref = ticker_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ticker_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTicker(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ticker_ = value;
        onChanged();
        return this;
      }
      public Builder clearTicker() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ticker_ = getDefaultInstance().getTicker();
        onChanged();
        return this;
      }
      void setTicker(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        ticker_ = value;
        onChanged();
      }
      
      // repeated .BE.DataBookEntry AskBook = 2;
      private java.util.List<BE.BEDataBook.DataBookEntry> askBook_ =
        java.util.Collections.emptyList();
      private void ensureAskBookIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          askBook_ = new java.util.ArrayList<BE.BEDataBook.DataBookEntry>(askBook_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          BE.BEDataBook.DataBookEntry, BE.BEDataBook.DataBookEntry.Builder, BE.BEDataBook.DataBookEntryOrBuilder> askBookBuilder_;
      
      public java.util.List<BE.BEDataBook.DataBookEntry> getAskBookList() {
        if (askBookBuilder_ == null) {
          return java.util.Collections.unmodifiableList(askBook_);
        } else {
          return askBookBuilder_.getMessageList();
        }
      }
      public int getAskBookCount() {
        if (askBookBuilder_ == null) {
          return askBook_.size();
        } else {
          return askBookBuilder_.getCount();
        }
      }
      public BE.BEDataBook.DataBookEntry getAskBook(int index) {
        if (askBookBuilder_ == null) {
          return askBook_.get(index);
        } else {
          return askBookBuilder_.getMessage(index);
        }
      }
      public Builder setAskBook(
          int index, BE.BEDataBook.DataBookEntry value) {
        if (askBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAskBookIsMutable();
          askBook_.set(index, value);
          onChanged();
        } else {
          askBookBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAskBook(
          int index, BE.BEDataBook.DataBookEntry.Builder builderForValue) {
        if (askBookBuilder_ == null) {
          ensureAskBookIsMutable();
          askBook_.set(index, builderForValue.build());
          onChanged();
        } else {
          askBookBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAskBook(BE.BEDataBook.DataBookEntry value) {
        if (askBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAskBookIsMutable();
          askBook_.add(value);
          onChanged();
        } else {
          askBookBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAskBook(
          int index, BE.BEDataBook.DataBookEntry value) {
        if (askBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAskBookIsMutable();
          askBook_.add(index, value);
          onChanged();
        } else {
          askBookBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAskBook(
          BE.BEDataBook.DataBookEntry.Builder builderForValue) {
        if (askBookBuilder_ == null) {
          ensureAskBookIsMutable();
          askBook_.add(builderForValue.build());
          onChanged();
        } else {
          askBookBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAskBook(
          int index, BE.BEDataBook.DataBookEntry.Builder builderForValue) {
        if (askBookBuilder_ == null) {
          ensureAskBookIsMutable();
          askBook_.add(index, builderForValue.build());
          onChanged();
        } else {
          askBookBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAskBook(
          java.lang.Iterable<? extends BE.BEDataBook.DataBookEntry> values) {
        if (askBookBuilder_ == null) {
          ensureAskBookIsMutable();
          super.addAll(values, askBook_);
          onChanged();
        } else {
          askBookBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAskBook() {
        if (askBookBuilder_ == null) {
          askBook_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          askBookBuilder_.clear();
        }
        return this;
      }
      public Builder removeAskBook(int index) {
        if (askBookBuilder_ == null) {
          ensureAskBookIsMutable();
          askBook_.remove(index);
          onChanged();
        } else {
          askBookBuilder_.remove(index);
        }
        return this;
      }
      public BE.BEDataBook.DataBookEntry.Builder getAskBookBuilder(
          int index) {
        return getAskBookFieldBuilder().getBuilder(index);
      }
      public BE.BEDataBook.DataBookEntryOrBuilder getAskBookOrBuilder(
          int index) {
        if (askBookBuilder_ == null) {
          return askBook_.get(index);  } else {
          return askBookBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends BE.BEDataBook.DataBookEntryOrBuilder> 
           getAskBookOrBuilderList() {
        if (askBookBuilder_ != null) {
          return askBookBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(askBook_);
        }
      }
      public BE.BEDataBook.DataBookEntry.Builder addAskBookBuilder() {
        return getAskBookFieldBuilder().addBuilder(
            BE.BEDataBook.DataBookEntry.getDefaultInstance());
      }
      public BE.BEDataBook.DataBookEntry.Builder addAskBookBuilder(
          int index) {
        return getAskBookFieldBuilder().addBuilder(
            index, BE.BEDataBook.DataBookEntry.getDefaultInstance());
      }
      public java.util.List<BE.BEDataBook.DataBookEntry.Builder> 
           getAskBookBuilderList() {
        return getAskBookFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          BE.BEDataBook.DataBookEntry, BE.BEDataBook.DataBookEntry.Builder, BE.BEDataBook.DataBookEntryOrBuilder> 
          getAskBookFieldBuilder() {
        if (askBookBuilder_ == null) {
          askBookBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              BE.BEDataBook.DataBookEntry, BE.BEDataBook.DataBookEntry.Builder, BE.BEDataBook.DataBookEntryOrBuilder>(
                  askBook_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          askBook_ = null;
        }
        return askBookBuilder_;
      }
      
      // repeated .BE.DataBookEntry BidBook = 3;
      private java.util.List<BE.BEDataBook.DataBookEntry> bidBook_ =
        java.util.Collections.emptyList();
      private void ensureBidBookIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          bidBook_ = new java.util.ArrayList<BE.BEDataBook.DataBookEntry>(bidBook_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          BE.BEDataBook.DataBookEntry, BE.BEDataBook.DataBookEntry.Builder, BE.BEDataBook.DataBookEntryOrBuilder> bidBookBuilder_;
      
      public java.util.List<BE.BEDataBook.DataBookEntry> getBidBookList() {
        if (bidBookBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bidBook_);
        } else {
          return bidBookBuilder_.getMessageList();
        }
      }
      public int getBidBookCount() {
        if (bidBookBuilder_ == null) {
          return bidBook_.size();
        } else {
          return bidBookBuilder_.getCount();
        }
      }
      public BE.BEDataBook.DataBookEntry getBidBook(int index) {
        if (bidBookBuilder_ == null) {
          return bidBook_.get(index);
        } else {
          return bidBookBuilder_.getMessage(index);
        }
      }
      public Builder setBidBook(
          int index, BE.BEDataBook.DataBookEntry value) {
        if (bidBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidBookIsMutable();
          bidBook_.set(index, value);
          onChanged();
        } else {
          bidBookBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBidBook(
          int index, BE.BEDataBook.DataBookEntry.Builder builderForValue) {
        if (bidBookBuilder_ == null) {
          ensureBidBookIsMutable();
          bidBook_.set(index, builderForValue.build());
          onChanged();
        } else {
          bidBookBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBidBook(BE.BEDataBook.DataBookEntry value) {
        if (bidBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidBookIsMutable();
          bidBook_.add(value);
          onChanged();
        } else {
          bidBookBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBidBook(
          int index, BE.BEDataBook.DataBookEntry value) {
        if (bidBookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidBookIsMutable();
          bidBook_.add(index, value);
          onChanged();
        } else {
          bidBookBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBidBook(
          BE.BEDataBook.DataBookEntry.Builder builderForValue) {
        if (bidBookBuilder_ == null) {
          ensureBidBookIsMutable();
          bidBook_.add(builderForValue.build());
          onChanged();
        } else {
          bidBookBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBidBook(
          int index, BE.BEDataBook.DataBookEntry.Builder builderForValue) {
        if (bidBookBuilder_ == null) {
          ensureBidBookIsMutable();
          bidBook_.add(index, builderForValue.build());
          onChanged();
        } else {
          bidBookBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBidBook(
          java.lang.Iterable<? extends BE.BEDataBook.DataBookEntry> values) {
        if (bidBookBuilder_ == null) {
          ensureBidBookIsMutable();
          super.addAll(values, bidBook_);
          onChanged();
        } else {
          bidBookBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBidBook() {
        if (bidBookBuilder_ == null) {
          bidBook_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          bidBookBuilder_.clear();
        }
        return this;
      }
      public Builder removeBidBook(int index) {
        if (bidBookBuilder_ == null) {
          ensureBidBookIsMutable();
          bidBook_.remove(index);
          onChanged();
        } else {
          bidBookBuilder_.remove(index);
        }
        return this;
      }
      public BE.BEDataBook.DataBookEntry.Builder getBidBookBuilder(
          int index) {
        return getBidBookFieldBuilder().getBuilder(index);
      }
      public BE.BEDataBook.DataBookEntryOrBuilder getBidBookOrBuilder(
          int index) {
        if (bidBookBuilder_ == null) {
          return bidBook_.get(index);  } else {
          return bidBookBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends BE.BEDataBook.DataBookEntryOrBuilder> 
           getBidBookOrBuilderList() {
        if (bidBookBuilder_ != null) {
          return bidBookBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bidBook_);
        }
      }
      public BE.BEDataBook.DataBookEntry.Builder addBidBookBuilder() {
        return getBidBookFieldBuilder().addBuilder(
            BE.BEDataBook.DataBookEntry.getDefaultInstance());
      }
      public BE.BEDataBook.DataBookEntry.Builder addBidBookBuilder(
          int index) {
        return getBidBookFieldBuilder().addBuilder(
            index, BE.BEDataBook.DataBookEntry.getDefaultInstance());
      }
      public java.util.List<BE.BEDataBook.DataBookEntry.Builder> 
           getBidBookBuilderList() {
        return getBidBookFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          BE.BEDataBook.DataBookEntry, BE.BEDataBook.DataBookEntry.Builder, BE.BEDataBook.DataBookEntryOrBuilder> 
          getBidBookFieldBuilder() {
        if (bidBookBuilder_ == null) {
          bidBookBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              BE.BEDataBook.DataBookEntry, BE.BEDataBook.DataBookEntry.Builder, BE.BEDataBook.DataBookEntryOrBuilder>(
                  bidBook_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          bidBook_ = null;
        }
        return bidBookBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:BE.DataBook)
    }
    
    static {
      defaultInstance = new DataBook(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.DataBook)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_DataBookEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_DataBookEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_DataBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_DataBook_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030protos/BE.DataBook.proto\022\002BE\"\274\t\n\rDataB" +
      "ookEntry\022\021\n\tTimeStamp\030\001 \002(\003\022\020\n\010Quantity\030" +
      "\002 \002(\001\022\r\n\005Price\030\003 \002(\001\022\020\n\010IdBroker\030\004 \002(\t\022\020" +
      "\n\010Position\030\005 \002(\003\022B\n\016QuoteCondition\030\006 \001(\016" +
      "2!.BE.DataBookEntry.EQuoteCondition:\007REG" +
      "ULAR\"\216\010\n\017EQuoteCondition\022\013\n\007REGULAR\020\001\022\022\n" +
      "\016BIDASKAUTOEXEC\020\002\022\014\n\010ROTATION\020\003\022\021\n\rSPECI" +
      "ALISTASK\020\004\022\021\n\rSPECIALISTBID\020\005\022\n\n\006LOCKED\020" +
      "\006\022\016\n\nFASTMARKET\020\007\022\024\n\020SPECIALISTBIDASK\020\010\022" +
      "\013\n\007ONESIDE\020\t\022\020\n\014OPENINGQUOTE\020\n\022\020\n\014CLOSIN",
      "GQUOTE\020\013\022\025\n\021MARKETMAKERCLOSED\020\014\022\016\n\nDEPTH" +
      "ONASK\020\r\022\016\n\nDEPTHONBID\020\016\022\021\n\rDEPTHONBIDASK" +
      "\020\017\022\t\n\005TIER3\020\020\022\013\n\007CROSSED\020\021\022\n\n\006HALTED\020\022\022\023" +
      "\n\017OPERATIONALHALT\020\023\022\013\n\007NEWSOUT\020\024\022\017\n\013NEWS" +
      "PENDING\020\025\022\013\n\007NONFIRM\020\026\022\020\n\014DUETORELATED\020\027" +
      "\022\n\n\006RESUME\020\030\022\022\n\016NOMARKETMAKERS\020\031\022\022\n\016ORDE" +
      "RIMBALANCE\020\032\022\017\n\013ORDERINFLUX\020\033\022\r\n\tINDICAT" +
      "ED\020\034\022\013\n\007PREOPEN\020\035\022\022\n\016INVIEWOFCOMMON\020\036\022\026\n" +
      "\022RELATEDNEWSPENDING\020\037\022\022\n\016RELATEDNEWSOUT\020" +
      " \022\022\n\016ADDITIONALINFO\020!\022\023\n\017RELATEDADDLINFO",
      "\020\"\022\020\n\014NOOPENRESUME\020#\022\013\n\007DELETED\020$\022\022\n\016REG" +
      "ULATORYHALT\020%\022\021\n\rSECSUSPENSION\020&\022\020\n\014NONC" +
      "OMLIANCE\020\'\022\025\n\021FILINGSNOTCURRENT\020(\022\017\n\013CAT" +
      "S_HALTED\020)\022\010\n\004CATS\020*\022\020\n\014EXDIVORSPLIT\020+\022\016" +
      "\n\nUNASSIGNED\020,\022\016\n\nINSIDEOPEN\020-\022\020\n\014INSIDE" +
      "CLOSED\020.\022\017\n\013OFFERWANTED\020/\022\r\n\tBIDWANTED\0200" +
      "\022\010\n\004CASH\0201\022\014\n\010INACTIVE\0202\022\017\n\013NATIONALBBO\020" +
      "3\022\013\n\007NOMINAL\0204\022\013\n\007CABINET\0205\022\022\n\016NOMINALCA" +
      "BINET\0206\022\016\n\nBLANKPRICE\0207\022\016\n\nSLOWBIDASK\0208\022" +
      "\014\n\010SLOWLIST\0209\022\013\n\007SLOWBID\020:\022\013\n\007SLOWASK\020;\022",
      "\022\n\016BIDOFFERWANTED\020<\022\014\n\010SUBPENNY\020=\022\n\n\006NON" +
      "BBO\020>\"b\n\010DataBook\022\016\n\006Ticker\030\001 \002(\t\022\"\n\007Ask" +
      "Book\030\002 \003(\0132\021.BE.DataBookEntry\022\"\n\007BidBook" +
      "\030\003 \003(\0132\021.BE.DataBookEntry"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BE_DataBookEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BE_DataBookEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_DataBookEntry_descriptor,
              new java.lang.String[] { "TimeStamp", "Quantity", "Price", "IdBroker", "Position", "QuoteCondition", },
              BE.BEDataBook.DataBookEntry.class,
              BE.BEDataBook.DataBookEntry.Builder.class);
          internal_static_BE_DataBook_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BE_DataBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_DataBook_descriptor,
              new java.lang.String[] { "Ticker", "AskBook", "BidBook", },
              BE.BEDataBook.DataBook.class,
              BE.BEDataBook.DataBook.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
