// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BE.OrderList.proto

package BE;

public final class BEOrderList {
  private BEOrderList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataOrderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string orderId = 1;
    boolean hasOrderId();
    String getOrderId();
    
    // required string clientId = 2;
    boolean hasClientId();
    String getClientId();
    
    // required int64 entrytime = 3;
    boolean hasEntrytime();
    long getEntrytime();
    
    // required string symbol = 4;
    boolean hasSymbol();
    String getSymbol();
    
    // optional double price = 5 [default = 0];
    boolean hasPrice();
    double getPrice();
    
    // optional double stoppx = 6 [default = 0];
    boolean hasStoppx();
    double getStoppx();
    
    // required int32 side = 7;
    boolean hasSide();
    int getSide();
    
    // required int32 type = 8;
    boolean hasType();
    int getType();
    
    // optional int64 quantity = 9 [default = 0];
    boolean hasQuantity();
    long getQuantity();
    
    // optional int64 minqty = 10 [default = 0];
    boolean hasMinqty();
    long getMinqty();
    
    // optional int64 openqty = 11 [default = 0];
    boolean hasOpenqty();
    long getOpenqty();
    
    // required string exchange = 12;
    boolean hasExchange();
    String getExchange();
    
    // required string accountId = 13;
    boolean hasAccountId();
    String getAccountId();
    
    // required int32 validity = 14;
    boolean hasValidity();
    int getValidity();
    
    // optional string date = 15;
    boolean hasDate();
    String getDate();
    
    // optional int64 qtyExecuted = 17;
    boolean hasQtyExecuted();
    long getQtyExecuted();
    
    // optional int64 qtyRemaining = 18;
    boolean hasQtyRemaining();
    long getQtyRemaining();
    
    // optional double avgPrice = 19;
    boolean hasAvgPrice();
    double getAvgPrice();
    
    // required int32 status = 20;
    boolean hasStatus();
    int getStatus();
    
    // optional string RejectReason = 21;
    boolean hasRejectReason();
    String getRejectReason();
    
    // optional double lastPrice = 22 [default = 0];
    boolean hasLastPrice();
    double getLastPrice();
    
    // optional double lastShares = 23 [default = 0];
    boolean hasLastShares();
    double getLastShares();
    
    // required string route = 24;
    boolean hasRoute();
    String getRoute();
    
    // required string broker = 25;
    boolean hasBroker();
    String getBroker();
  }
  public static final class DataOrder extends
      com.google.protobuf.GeneratedMessage
      implements DataOrderOrBuilder {
    // Use DataOrder.newBuilder() to construct.
    private DataOrder(Builder builder) {
      super(builder);
    }
    private DataOrder(boolean noInit) {}
    
    private static final DataOrder defaultInstance;
    public static DataOrder getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataOrder getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEOrderList.internal_static_BE_DataOrder_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEOrderList.internal_static_BE_DataOrder_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string orderId = 1;
    public static final int ORDERID_FIELD_NUMBER = 1;
    private java.lang.Object orderId_;
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          orderId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string clientId = 2;
    public static final int CLIENTID_FIELD_NUMBER = 2;
    private java.lang.Object clientId_;
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clientId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 entrytime = 3;
    public static final int ENTRYTIME_FIELD_NUMBER = 3;
    private long entrytime_;
    public boolean hasEntrytime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getEntrytime() {
      return entrytime_;
    }
    
    // required string symbol = 4;
    public static final int SYMBOL_FIELD_NUMBER = 4;
    private java.lang.Object symbol_;
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          symbol_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double price = 5 [default = 0];
    public static final int PRICE_FIELD_NUMBER = 5;
    private double price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getPrice() {
      return price_;
    }
    
    // optional double stoppx = 6 [default = 0];
    public static final int STOPPX_FIELD_NUMBER = 6;
    private double stoppx_;
    public boolean hasStoppx() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getStoppx() {
      return stoppx_;
    }
    
    // required int32 side = 7;
    public static final int SIDE_FIELD_NUMBER = 7;
    private int side_;
    public boolean hasSide() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getSide() {
      return side_;
    }
    
    // required int32 type = 8;
    public static final int TYPE_FIELD_NUMBER = 8;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getType() {
      return type_;
    }
    
    // optional int64 quantity = 9 [default = 0];
    public static final int QUANTITY_FIELD_NUMBER = 9;
    private long quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getQuantity() {
      return quantity_;
    }
    
    // optional int64 minqty = 10 [default = 0];
    public static final int MINQTY_FIELD_NUMBER = 10;
    private long minqty_;
    public boolean hasMinqty() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public long getMinqty() {
      return minqty_;
    }
    
    // optional int64 openqty = 11 [default = 0];
    public static final int OPENQTY_FIELD_NUMBER = 11;
    private long openqty_;
    public boolean hasOpenqty() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public long getOpenqty() {
      return openqty_;
    }
    
    // required string exchange = 12;
    public static final int EXCHANGE_FIELD_NUMBER = 12;
    private java.lang.Object exchange_;
    public boolean hasExchange() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          exchange_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string accountId = 13;
    public static final int ACCOUNTID_FIELD_NUMBER = 13;
    private java.lang.Object accountId_;
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 validity = 14;
    public static final int VALIDITY_FIELD_NUMBER = 14;
    private int validity_;
    public boolean hasValidity() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getValidity() {
      return validity_;
    }
    
    // optional string date = 15;
    public static final int DATE_FIELD_NUMBER = 15;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 qtyExecuted = 17;
    public static final int QTYEXECUTED_FIELD_NUMBER = 17;
    private long qtyExecuted_;
    public boolean hasQtyExecuted() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public long getQtyExecuted() {
      return qtyExecuted_;
    }
    
    // optional int64 qtyRemaining = 18;
    public static final int QTYREMAINING_FIELD_NUMBER = 18;
    private long qtyRemaining_;
    public boolean hasQtyRemaining() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public long getQtyRemaining() {
      return qtyRemaining_;
    }
    
    // optional double avgPrice = 19;
    public static final int AVGPRICE_FIELD_NUMBER = 19;
    private double avgPrice_;
    public boolean hasAvgPrice() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public double getAvgPrice() {
      return avgPrice_;
    }
    
    // required int32 status = 20;
    public static final int STATUS_FIELD_NUMBER = 20;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional string RejectReason = 21;
    public static final int REJECTREASON_FIELD_NUMBER = 21;
    private java.lang.Object rejectReason_;
    public boolean hasRejectReason() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    public String getRejectReason() {
      java.lang.Object ref = rejectReason_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rejectReason_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRejectReasonBytes() {
      java.lang.Object ref = rejectReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rejectReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double lastPrice = 22 [default = 0];
    public static final int LASTPRICE_FIELD_NUMBER = 22;
    private double lastPrice_;
    public boolean hasLastPrice() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    public double getLastPrice() {
      return lastPrice_;
    }
    
    // optional double lastShares = 23 [default = 0];
    public static final int LASTSHARES_FIELD_NUMBER = 23;
    private double lastShares_;
    public boolean hasLastShares() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    public double getLastShares() {
      return lastShares_;
    }
    
    // required string route = 24;
    public static final int ROUTE_FIELD_NUMBER = 24;
    private java.lang.Object route_;
    public boolean hasRoute() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    public String getRoute() {
      java.lang.Object ref = route_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          route_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string broker = 25;
    public static final int BROKER_FIELD_NUMBER = 25;
    private java.lang.Object broker_;
    public boolean hasBroker() {
      return ((bitField0_ & 0x00800000) == 0x00800000);
    }
    public String getBroker() {
      java.lang.Object ref = broker_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          broker_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBrokerBytes() {
      java.lang.Object ref = broker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        broker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      orderId_ = "";
      clientId_ = "";
      entrytime_ = 0L;
      symbol_ = "";
      price_ = 0D;
      stoppx_ = 0D;
      side_ = 0;
      type_ = 0;
      quantity_ = 0L;
      minqty_ = 0L;
      openqty_ = 0L;
      exchange_ = "";
      accountId_ = "";
      validity_ = 0;
      date_ = "";
      qtyExecuted_ = 0L;
      qtyRemaining_ = 0L;
      avgPrice_ = 0D;
      status_ = 0;
      rejectReason_ = "";
      lastPrice_ = 0D;
      lastShares_ = 0D;
      route_ = "";
      broker_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntrytime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSymbol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSide()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExchange()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValidity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBroker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, entrytime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSymbolBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, price_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, stoppx_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, side_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, type_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, quantity_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, minqty_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, openqty_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getExchangeBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, validity_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getDateBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt64(17, qtyExecuted_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt64(18, qtyRemaining_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeDouble(19, avgPrice_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeInt32(20, status_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeBytes(21, getRejectReasonBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeDouble(22, lastPrice_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeDouble(23, lastShares_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeBytes(24, getRouteBytes());
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        output.writeBytes(25, getBrokerBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, entrytime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSymbolBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, price_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, stoppx_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, side_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, type_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, quantity_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, minqty_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, openqty_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getExchangeBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, validity_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getDateBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, qtyExecuted_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(18, qtyRemaining_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(19, avgPrice_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, status_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(21, getRejectReasonBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(22, lastPrice_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(23, lastShares_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(24, getRouteBytes());
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(25, getBrokerBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEOrderList.DataOrder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEOrderList.DataOrder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderList.DataOrder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEOrderList.DataOrder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderList.DataOrder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEOrderList.DataOrder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderList.DataOrder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEOrderList.DataOrder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEOrderList.DataOrder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEOrderList.DataOrder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEOrderList.DataOrder prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEOrderList.DataOrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEOrderList.internal_static_BE_DataOrder_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEOrderList.internal_static_BE_DataOrder_fieldAccessorTable;
      }
      
      // Construct using BE.BEOrderList.DataOrder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        entrytime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        symbol_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        stoppx_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        side_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        quantity_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        minqty_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        openqty_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        exchange_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        accountId_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        validity_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        qtyExecuted_ = 0L;
        bitField0_ = (bitField0_ & ~0x00008000);
        qtyRemaining_ = 0L;
        bitField0_ = (bitField0_ & ~0x00010000);
        avgPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00020000);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        rejectReason_ = "";
        bitField0_ = (bitField0_ & ~0x00080000);
        lastPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00100000);
        lastShares_ = 0D;
        bitField0_ = (bitField0_ & ~0x00200000);
        route_ = "";
        bitField0_ = (bitField0_ & ~0x00400000);
        broker_ = "";
        bitField0_ = (bitField0_ & ~0x00800000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEOrderList.DataOrder.getDescriptor();
      }
      
      public BE.BEOrderList.DataOrder getDefaultInstanceForType() {
        return BE.BEOrderList.DataOrder.getDefaultInstance();
      }
      
      public BE.BEOrderList.DataOrder build() {
        BE.BEOrderList.DataOrder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEOrderList.DataOrder buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEOrderList.DataOrder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEOrderList.DataOrder buildPartial() {
        BE.BEOrderList.DataOrder result = new BE.BEOrderList.DataOrder(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.entrytime_ = entrytime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.symbol_ = symbol_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stoppx_ = stoppx_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.side_ = side_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.minqty_ = minqty_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.openqty_ = openqty_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.exchange_ = exchange_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.validity_ = validity_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.qtyExecuted_ = qtyExecuted_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.qtyRemaining_ = qtyRemaining_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.avgPrice_ = avgPrice_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.rejectReason_ = rejectReason_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.lastPrice_ = lastPrice_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.lastShares_ = lastShares_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.route_ = route_;
        if (((from_bitField0_ & 0x00800000) == 0x00800000)) {
          to_bitField0_ |= 0x00800000;
        }
        result.broker_ = broker_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEOrderList.DataOrder) {
          return mergeFrom((BE.BEOrderList.DataOrder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEOrderList.DataOrder other) {
        if (other == BE.BEOrderList.DataOrder.getDefaultInstance()) return this;
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasEntrytime()) {
          setEntrytime(other.getEntrytime());
        }
        if (other.hasSymbol()) {
          setSymbol(other.getSymbol());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasStoppx()) {
          setStoppx(other.getStoppx());
        }
        if (other.hasSide()) {
          setSide(other.getSide());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasMinqty()) {
          setMinqty(other.getMinqty());
        }
        if (other.hasOpenqty()) {
          setOpenqty(other.getOpenqty());
        }
        if (other.hasExchange()) {
          setExchange(other.getExchange());
        }
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasValidity()) {
          setValidity(other.getValidity());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasQtyExecuted()) {
          setQtyExecuted(other.getQtyExecuted());
        }
        if (other.hasQtyRemaining()) {
          setQtyRemaining(other.getQtyRemaining());
        }
        if (other.hasAvgPrice()) {
          setAvgPrice(other.getAvgPrice());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasRejectReason()) {
          setRejectReason(other.getRejectReason());
        }
        if (other.hasLastPrice()) {
          setLastPrice(other.getLastPrice());
        }
        if (other.hasLastShares()) {
          setLastShares(other.getLastShares());
        }
        if (other.hasRoute()) {
          setRoute(other.getRoute());
        }
        if (other.hasBroker()) {
          setBroker(other.getBroker());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOrderId()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        if (!hasEntrytime()) {
          
          return false;
        }
        if (!hasSymbol()) {
          
          return false;
        }
        if (!hasSide()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasExchange()) {
          
          return false;
        }
        if (!hasAccountId()) {
          
          return false;
        }
        if (!hasValidity()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasRoute()) {
          
          return false;
        }
        if (!hasBroker()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              orderId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              clientId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              entrytime_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              symbol_ = input.readBytes();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              price_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              stoppx_ = input.readDouble();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              side_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              type_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              quantity_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              minqty_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              openqty_ = input.readInt64();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              exchange_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              accountId_ = input.readBytes();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              validity_ = input.readInt32();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              date_ = input.readBytes();
              break;
            }
            case 136: {
              bitField0_ |= 0x00008000;
              qtyExecuted_ = input.readInt64();
              break;
            }
            case 144: {
              bitField0_ |= 0x00010000;
              qtyRemaining_ = input.readInt64();
              break;
            }
            case 153: {
              bitField0_ |= 0x00020000;
              avgPrice_ = input.readDouble();
              break;
            }
            case 160: {
              bitField0_ |= 0x00040000;
              status_ = input.readInt32();
              break;
            }
            case 170: {
              bitField0_ |= 0x00080000;
              rejectReason_ = input.readBytes();
              break;
            }
            case 177: {
              bitField0_ |= 0x00100000;
              lastPrice_ = input.readDouble();
              break;
            }
            case 185: {
              bitField0_ |= 0x00200000;
              lastShares_ = input.readDouble();
              break;
            }
            case 194: {
              bitField0_ |= 0x00400000;
              route_ = input.readBytes();
              break;
            }
            case 202: {
              bitField0_ |= 0x00800000;
              broker_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string orderId = 1;
      private java.lang.Object orderId_ = "";
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOrderId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      void setOrderId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
      }
      
      // required string clientId = 2;
      private java.lang.Object clientId_ = "";
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClientId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      void setClientId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        clientId_ = value;
        onChanged();
      }
      
      // required int64 entrytime = 3;
      private long entrytime_ ;
      public boolean hasEntrytime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getEntrytime() {
        return entrytime_;
      }
      public Builder setEntrytime(long value) {
        bitField0_ |= 0x00000004;
        entrytime_ = value;
        onChanged();
        return this;
      }
      public Builder clearEntrytime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        entrytime_ = 0L;
        onChanged();
        return this;
      }
      
      // required string symbol = 4;
      private java.lang.Object symbol_ = "";
      public boolean hasSymbol() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSymbol(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        symbol_ = value;
        onChanged();
        return this;
      }
      public Builder clearSymbol() {
        bitField0_ = (bitField0_ & ~0x00000008);
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      void setSymbol(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        symbol_ = value;
        onChanged();
      }
      
      // optional double price = 5 [default = 0];
      private double price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getPrice() {
        return price_;
      }
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000010;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        price_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double stoppx = 6 [default = 0];
      private double stoppx_ ;
      public boolean hasStoppx() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getStoppx() {
        return stoppx_;
      }
      public Builder setStoppx(double value) {
        bitField0_ |= 0x00000020;
        stoppx_ = value;
        onChanged();
        return this;
      }
      public Builder clearStoppx() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stoppx_ = 0D;
        onChanged();
        return this;
      }
      
      // required int32 side = 7;
      private int side_ ;
      public boolean hasSide() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getSide() {
        return side_;
      }
      public Builder setSide(int value) {
        bitField0_ |= 0x00000040;
        side_ = value;
        onChanged();
        return this;
      }
      public Builder clearSide() {
        bitField0_ = (bitField0_ & ~0x00000040);
        side_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 type = 8;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000080;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 quantity = 9 [default = 0];
      private long quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(long value) {
        bitField0_ |= 0x00000100;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000100);
        quantity_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 minqty = 10 [default = 0];
      private long minqty_ ;
      public boolean hasMinqty() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public long getMinqty() {
        return minqty_;
      }
      public Builder setMinqty(long value) {
        bitField0_ |= 0x00000200;
        minqty_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinqty() {
        bitField0_ = (bitField0_ & ~0x00000200);
        minqty_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 openqty = 11 [default = 0];
      private long openqty_ ;
      public boolean hasOpenqty() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public long getOpenqty() {
        return openqty_;
      }
      public Builder setOpenqty(long value) {
        bitField0_ |= 0x00000400;
        openqty_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpenqty() {
        bitField0_ = (bitField0_ & ~0x00000400);
        openqty_ = 0L;
        onChanged();
        return this;
      }
      
      // required string exchange = 12;
      private java.lang.Object exchange_ = "";
      public boolean hasExchange() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          exchange_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExchange(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        exchange_ = value;
        onChanged();
        return this;
      }
      public Builder clearExchange() {
        bitField0_ = (bitField0_ & ~0x00000800);
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      void setExchange(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        exchange_ = value;
        onChanged();
      }
      
      // required string accountId = 13;
      private java.lang.Object accountId_ = "";
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        accountId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        accountId_ = getDefaultInstance().getAccountId();
        onChanged();
        return this;
      }
      void setAccountId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        accountId_ = value;
        onChanged();
      }
      
      // required int32 validity = 14;
      private int validity_ ;
      public boolean hasValidity() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getValidity() {
        return validity_;
      }
      public Builder setValidity(int value) {
        bitField0_ |= 0x00002000;
        validity_ = value;
        onChanged();
        return this;
      }
      public Builder clearValidity() {
        bitField0_ = (bitField0_ & ~0x00002000);
        validity_ = 0;
        onChanged();
        return this;
      }
      
      // optional string date = 15;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00004000);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00004000;
        date_ = value;
        onChanged();
      }
      
      // optional int64 qtyExecuted = 17;
      private long qtyExecuted_ ;
      public boolean hasQtyExecuted() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public long getQtyExecuted() {
        return qtyExecuted_;
      }
      public Builder setQtyExecuted(long value) {
        bitField0_ |= 0x00008000;
        qtyExecuted_ = value;
        onChanged();
        return this;
      }
      public Builder clearQtyExecuted() {
        bitField0_ = (bitField0_ & ~0x00008000);
        qtyExecuted_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 qtyRemaining = 18;
      private long qtyRemaining_ ;
      public boolean hasQtyRemaining() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public long getQtyRemaining() {
        return qtyRemaining_;
      }
      public Builder setQtyRemaining(long value) {
        bitField0_ |= 0x00010000;
        qtyRemaining_ = value;
        onChanged();
        return this;
      }
      public Builder clearQtyRemaining() {
        bitField0_ = (bitField0_ & ~0x00010000);
        qtyRemaining_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double avgPrice = 19;
      private double avgPrice_ ;
      public boolean hasAvgPrice() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public double getAvgPrice() {
        return avgPrice_;
      }
      public Builder setAvgPrice(double value) {
        bitField0_ |= 0x00020000;
        avgPrice_ = value;
        onChanged();
        return this;
      }
      public Builder clearAvgPrice() {
        bitField0_ = (bitField0_ & ~0x00020000);
        avgPrice_ = 0D;
        onChanged();
        return this;
      }
      
      // required int32 status = 20;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00040000;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00040000);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // optional string RejectReason = 21;
      private java.lang.Object rejectReason_ = "";
      public boolean hasRejectReason() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      public String getRejectReason() {
        java.lang.Object ref = rejectReason_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rejectReason_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRejectReason(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        rejectReason_ = value;
        onChanged();
        return this;
      }
      public Builder clearRejectReason() {
        bitField0_ = (bitField0_ & ~0x00080000);
        rejectReason_ = getDefaultInstance().getRejectReason();
        onChanged();
        return this;
      }
      void setRejectReason(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00080000;
        rejectReason_ = value;
        onChanged();
      }
      
      // optional double lastPrice = 22 [default = 0];
      private double lastPrice_ ;
      public boolean hasLastPrice() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      public double getLastPrice() {
        return lastPrice_;
      }
      public Builder setLastPrice(double value) {
        bitField0_ |= 0x00100000;
        lastPrice_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastPrice() {
        bitField0_ = (bitField0_ & ~0x00100000);
        lastPrice_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double lastShares = 23 [default = 0];
      private double lastShares_ ;
      public boolean hasLastShares() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      public double getLastShares() {
        return lastShares_;
      }
      public Builder setLastShares(double value) {
        bitField0_ |= 0x00200000;
        lastShares_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastShares() {
        bitField0_ = (bitField0_ & ~0x00200000);
        lastShares_ = 0D;
        onChanged();
        return this;
      }
      
      // required string route = 24;
      private java.lang.Object route_ = "";
      public boolean hasRoute() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      public String getRoute() {
        java.lang.Object ref = route_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          route_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRoute(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00400000;
        route_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoute() {
        bitField0_ = (bitField0_ & ~0x00400000);
        route_ = getDefaultInstance().getRoute();
        onChanged();
        return this;
      }
      void setRoute(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00400000;
        route_ = value;
        onChanged();
      }
      
      // required string broker = 25;
      private java.lang.Object broker_ = "";
      public boolean hasBroker() {
        return ((bitField0_ & 0x00800000) == 0x00800000);
      }
      public String getBroker() {
        java.lang.Object ref = broker_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          broker_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBroker(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00800000;
        broker_ = value;
        onChanged();
        return this;
      }
      public Builder clearBroker() {
        bitField0_ = (bitField0_ & ~0x00800000);
        broker_ = getDefaultInstance().getBroker();
        onChanged();
        return this;
      }
      void setBroker(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00800000;
        broker_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:BE.DataOrder)
    }
    
    static {
      defaultInstance = new DataOrder(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.DataOrder)
  }
  
  public interface DataOrderListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .BE.DataOrder order = 1;
    java.util.List<BE.BEOrderList.DataOrder> 
        getOrderList();
    BE.BEOrderList.DataOrder getOrder(int index);
    int getOrderCount();
    java.util.List<? extends BE.BEOrderList.DataOrderOrBuilder> 
        getOrderOrBuilderList();
    BE.BEOrderList.DataOrderOrBuilder getOrderOrBuilder(
        int index);
  }
  public static final class DataOrderList extends
      com.google.protobuf.GeneratedMessage
      implements DataOrderListOrBuilder {
    // Use DataOrderList.newBuilder() to construct.
    private DataOrderList(Builder builder) {
      super(builder);
    }
    private DataOrderList(boolean noInit) {}
    
    private static final DataOrderList defaultInstance;
    public static DataOrderList getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataOrderList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEOrderList.internal_static_BE_DataOrderList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEOrderList.internal_static_BE_DataOrderList_fieldAccessorTable;
    }
    
    // repeated .BE.DataOrder order = 1;
    public static final int ORDER_FIELD_NUMBER = 1;
    private java.util.List<BE.BEOrderList.DataOrder> order_;
    public java.util.List<BE.BEOrderList.DataOrder> getOrderList() {
      return order_;
    }
    public java.util.List<? extends BE.BEOrderList.DataOrderOrBuilder> 
        getOrderOrBuilderList() {
      return order_;
    }
    public int getOrderCount() {
      return order_.size();
    }
    public BE.BEOrderList.DataOrder getOrder(int index) {
      return order_.get(index);
    }
    public BE.BEOrderList.DataOrderOrBuilder getOrderOrBuilder(
        int index) {
      return order_.get(index);
    }
    
    private void initFields() {
      order_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getOrderCount(); i++) {
        if (!getOrder(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < order_.size(); i++) {
        output.writeMessage(1, order_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < order_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, order_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEOrderList.DataOrderList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEOrderList.DataOrderList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderList.DataOrderList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEOrderList.DataOrderList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderList.DataOrderList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEOrderList.DataOrderList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderList.DataOrderList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEOrderList.DataOrderList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEOrderList.DataOrderList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEOrderList.DataOrderList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEOrderList.DataOrderList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEOrderList.DataOrderListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEOrderList.internal_static_BE_DataOrderList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEOrderList.internal_static_BE_DataOrderList_fieldAccessorTable;
      }
      
      // Construct using BE.BEOrderList.DataOrderList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOrderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (orderBuilder_ == null) {
          order_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          orderBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEOrderList.DataOrderList.getDescriptor();
      }
      
      public BE.BEOrderList.DataOrderList getDefaultInstanceForType() {
        return BE.BEOrderList.DataOrderList.getDefaultInstance();
      }
      
      public BE.BEOrderList.DataOrderList build() {
        BE.BEOrderList.DataOrderList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEOrderList.DataOrderList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEOrderList.DataOrderList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEOrderList.DataOrderList buildPartial() {
        BE.BEOrderList.DataOrderList result = new BE.BEOrderList.DataOrderList(this);
        int from_bitField0_ = bitField0_;
        if (orderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            order_ = java.util.Collections.unmodifiableList(order_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.order_ = order_;
        } else {
          result.order_ = orderBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEOrderList.DataOrderList) {
          return mergeFrom((BE.BEOrderList.DataOrderList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEOrderList.DataOrderList other) {
        if (other == BE.BEOrderList.DataOrderList.getDefaultInstance()) return this;
        if (orderBuilder_ == null) {
          if (!other.order_.isEmpty()) {
            if (order_.isEmpty()) {
              order_ = other.order_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrderIsMutable();
              order_.addAll(other.order_);
            }
            onChanged();
          }
        } else {
          if (!other.order_.isEmpty()) {
            if (orderBuilder_.isEmpty()) {
              orderBuilder_.dispose();
              orderBuilder_ = null;
              order_ = other.order_;
              bitField0_ = (bitField0_ & ~0x00000001);
              orderBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOrderFieldBuilder() : null;
            } else {
              orderBuilder_.addAllMessages(other.order_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getOrderCount(); i++) {
          if (!getOrder(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              BE.BEOrderList.DataOrder.Builder subBuilder = BE.BEOrderList.DataOrder.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOrder(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .BE.DataOrder order = 1;
      private java.util.List<BE.BEOrderList.DataOrder> order_ =
        java.util.Collections.emptyList();
      private void ensureOrderIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          order_ = new java.util.ArrayList<BE.BEOrderList.DataOrder>(order_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          BE.BEOrderList.DataOrder, BE.BEOrderList.DataOrder.Builder, BE.BEOrderList.DataOrderOrBuilder> orderBuilder_;
      
      public java.util.List<BE.BEOrderList.DataOrder> getOrderList() {
        if (orderBuilder_ == null) {
          return java.util.Collections.unmodifiableList(order_);
        } else {
          return orderBuilder_.getMessageList();
        }
      }
      public int getOrderCount() {
        if (orderBuilder_ == null) {
          return order_.size();
        } else {
          return orderBuilder_.getCount();
        }
      }
      public BE.BEOrderList.DataOrder getOrder(int index) {
        if (orderBuilder_ == null) {
          return order_.get(index);
        } else {
          return orderBuilder_.getMessage(index);
        }
      }
      public Builder setOrder(
          int index, BE.BEOrderList.DataOrder value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderIsMutable();
          order_.set(index, value);
          onChanged();
        } else {
          orderBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOrder(
          int index, BE.BEOrderList.DataOrder.Builder builderForValue) {
        if (orderBuilder_ == null) {
          ensureOrderIsMutable();
          order_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOrder(BE.BEOrderList.DataOrder value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderIsMutable();
          order_.add(value);
          onChanged();
        } else {
          orderBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOrder(
          int index, BE.BEOrderList.DataOrder value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderIsMutable();
          order_.add(index, value);
          onChanged();
        } else {
          orderBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOrder(
          BE.BEOrderList.DataOrder.Builder builderForValue) {
        if (orderBuilder_ == null) {
          ensureOrderIsMutable();
          order_.add(builderForValue.build());
          onChanged();
        } else {
          orderBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOrder(
          int index, BE.BEOrderList.DataOrder.Builder builderForValue) {
        if (orderBuilder_ == null) {
          ensureOrderIsMutable();
          order_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOrder(
          java.lang.Iterable<? extends BE.BEOrderList.DataOrder> values) {
        if (orderBuilder_ == null) {
          ensureOrderIsMutable();
          super.addAll(values, order_);
          onChanged();
        } else {
          orderBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOrder() {
        if (orderBuilder_ == null) {
          order_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          orderBuilder_.clear();
        }
        return this;
      }
      public Builder removeOrder(int index) {
        if (orderBuilder_ == null) {
          ensureOrderIsMutable();
          order_.remove(index);
          onChanged();
        } else {
          orderBuilder_.remove(index);
        }
        return this;
      }
      public BE.BEOrderList.DataOrder.Builder getOrderBuilder(
          int index) {
        return getOrderFieldBuilder().getBuilder(index);
      }
      public BE.BEOrderList.DataOrderOrBuilder getOrderOrBuilder(
          int index) {
        if (orderBuilder_ == null) {
          return order_.get(index);  } else {
          return orderBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends BE.BEOrderList.DataOrderOrBuilder> 
           getOrderOrBuilderList() {
        if (orderBuilder_ != null) {
          return orderBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(order_);
        }
      }
      public BE.BEOrderList.DataOrder.Builder addOrderBuilder() {
        return getOrderFieldBuilder().addBuilder(
            BE.BEOrderList.DataOrder.getDefaultInstance());
      }
      public BE.BEOrderList.DataOrder.Builder addOrderBuilder(
          int index) {
        return getOrderFieldBuilder().addBuilder(
            index, BE.BEOrderList.DataOrder.getDefaultInstance());
      }
      public java.util.List<BE.BEOrderList.DataOrder.Builder> 
           getOrderBuilderList() {
        return getOrderFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          BE.BEOrderList.DataOrder, BE.BEOrderList.DataOrder.Builder, BE.BEOrderList.DataOrderOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          orderBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              BE.BEOrderList.DataOrder, BE.BEOrderList.DataOrder.Builder, BE.BEOrderList.DataOrderOrBuilder>(
                  order_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          order_ = null;
        }
        return orderBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:BE.DataOrderList)
    }
    
    static {
      defaultInstance = new DataOrderList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.DataOrderList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_DataOrder_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_DataOrder_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_DataOrderList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_DataOrderList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protos/BE.OrderList.proto\022\002BE\"\302\003\n\tData" +
      "Order\022\017\n\007orderId\030\001 \002(\t\022\020\n\010clientId\030\002 \002(\t" +
      "\022\021\n\tentrytime\030\003 \002(\003\022\016\n\006symbol\030\004 \002(\t\022\020\n\005p" +
      "rice\030\005 \001(\001:\0010\022\021\n\006stoppx\030\006 \001(\001:\0010\022\014\n\004side" +
      "\030\007 \002(\005\022\014\n\004type\030\010 \002(\005\022\023\n\010quantity\030\t \001(\003:\001" +
      "0\022\021\n\006minqty\030\n \001(\003:\0010\022\022\n\007openqty\030\013 \001(\003:\0010" +
      "\022\020\n\010exchange\030\014 \002(\t\022\021\n\taccountId\030\r \002(\t\022\020\n" +
      "\010validity\030\016 \002(\005\022\014\n\004date\030\017 \001(\t\022\023\n\013qtyExec" +
      "uted\030\021 \001(\003\022\024\n\014qtyRemaining\030\022 \001(\003\022\020\n\010avgP" +
      "rice\030\023 \001(\001\022\016\n\006status\030\024 \002(\005\022\024\n\014RejectReas",
      "on\030\025 \001(\t\022\024\n\tlastPrice\030\026 \001(\001:\0010\022\025\n\nlastSh" +
      "ares\030\027 \001(\001:\0010\022\r\n\005route\030\030 \002(\t\022\016\n\006broker\030\031" +
      " \002(\t\"-\n\rDataOrderList\022\034\n\005order\030\001 \003(\0132\r.B" +
      "E.DataOrder"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BE_DataOrder_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BE_DataOrder_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_DataOrder_descriptor,
              new java.lang.String[] { "OrderId", "ClientId", "Entrytime", "Symbol", "Price", "Stoppx", "Side", "Type", "Quantity", "Minqty", "Openqty", "Exchange", "AccountId", "Validity", "Date", "QtyExecuted", "QtyRemaining", "AvgPrice", "Status", "RejectReason", "LastPrice", "LastShares", "Route", "Broker", },
              BE.BEOrderList.DataOrder.class,
              BE.BEOrderList.DataOrder.Builder.class);
          internal_static_BE_DataOrderList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BE_DataOrderList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_DataOrderList_descriptor,
              new java.lang.String[] { "Order", },
              BE.BEOrderList.DataOrderList.class,
              BE.BEOrderList.DataOrderList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
