// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BE.OrderRequest.proto

package BE;

public final class BEOrderRequest {
  private BEOrderRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 reqType = 1;
    boolean hasReqType();
    int getReqType();
    
    // required int64 time = 2;
    boolean hasTime();
    long getTime();
    
    // required string clientId = 3;
    boolean hasClientId();
    String getClientId();
    
    // required string orderId = 4;
    boolean hasOrderId();
    String getOrderId();
    
    // required string symbol = 5;
    boolean hasSymbol();
    String getSymbol();
    
    // optional double price = 6 [default = 0];
    boolean hasPrice();
    double getPrice();
    
    // optional double stoppx = 7 [default = 0];
    boolean hasStoppx();
    double getStoppx();
    
    // required int32 side = 8;
    boolean hasSide();
    int getSide();
    
    // required int32 type = 9;
    boolean hasType();
    int getType();
    
    // optional int64 quantity = 10 [default = 0];
    boolean hasQuantity();
    long getQuantity();
    
    // optional int64 minqty = 11 [default = 0];
    boolean hasMinqty();
    long getMinqty();
    
    // optional int64 openqty = 12 [default = 0];
    boolean hasOpenqty();
    long getOpenqty();
    
    // required string exchange = 13;
    boolean hasExchange();
    String getExchange();
    
    // required string accountId = 14;
    boolean hasAccountId();
    String getAccountId();
    
    // required int32 validity = 15;
    boolean hasValidity();
    int getValidity();
    
    // optional string validityDate = 16;
    boolean hasValidityDate();
    String getValidityDate();
    
    // required string route = 17;
    boolean hasRoute();
    String getRoute();
    
    // required string broker = 18;
    boolean hasBroker();
    String getBroker();
    
    // optional string portfolio = 19;
    boolean hasPortfolio();
    String getPortfolio();
    
    // optional string securityId = 20;
    boolean hasSecurityId();
    String getSecurityId();
    
    // optional string securityIdSource = 21;
    boolean hasSecurityIdSource();
    String getSecurityIdSource();
    
    // optional string securityExchange = 22;
    boolean hasSecurityExchange();
    String getSecurityExchange();
    
    // optional double lastPrice = 23;
    boolean hasLastPrice();
    double getLastPrice();
  }
  public static final class OrderRequest extends
      com.google.protobuf.GeneratedMessage
      implements OrderRequestOrBuilder {
    // Use OrderRequest.newBuilder() to construct.
    private OrderRequest(Builder builder) {
      super(builder);
    }
    private OrderRequest(boolean noInit) {}
    
    private static final OrderRequest defaultInstance;
    public static OrderRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public OrderRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEOrderRequest.internal_static_BE_OrderRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEOrderRequest.internal_static_BE_OrderRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private int reqType_;
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getReqType() {
      return reqType_;
    }
    
    // required int64 time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTime() {
      return time_;
    }
    
    // required string clientId = 3;
    public static final int CLIENTID_FIELD_NUMBER = 3;
    private java.lang.Object clientId_;
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clientId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string orderId = 4;
    public static final int ORDERID_FIELD_NUMBER = 4;
    private java.lang.Object orderId_;
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          orderId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string symbol = 5;
    public static final int SYMBOL_FIELD_NUMBER = 5;
    private java.lang.Object symbol_;
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          symbol_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double price = 6 [default = 0];
    public static final int PRICE_FIELD_NUMBER = 6;
    private double price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getPrice() {
      return price_;
    }
    
    // optional double stoppx = 7 [default = 0];
    public static final int STOPPX_FIELD_NUMBER = 7;
    private double stoppx_;
    public boolean hasStoppx() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getStoppx() {
      return stoppx_;
    }
    
    // required int32 side = 8;
    public static final int SIDE_FIELD_NUMBER = 8;
    private int side_;
    public boolean hasSide() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getSide() {
      return side_;
    }
    
    // required int32 type = 9;
    public static final int TYPE_FIELD_NUMBER = 9;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getType() {
      return type_;
    }
    
    // optional int64 quantity = 10 [default = 0];
    public static final int QUANTITY_FIELD_NUMBER = 10;
    private long quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public long getQuantity() {
      return quantity_;
    }
    
    // optional int64 minqty = 11 [default = 0];
    public static final int MINQTY_FIELD_NUMBER = 11;
    private long minqty_;
    public boolean hasMinqty() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public long getMinqty() {
      return minqty_;
    }
    
    // optional int64 openqty = 12 [default = 0];
    public static final int OPENQTY_FIELD_NUMBER = 12;
    private long openqty_;
    public boolean hasOpenqty() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public long getOpenqty() {
      return openqty_;
    }
    
    // required string exchange = 13;
    public static final int EXCHANGE_FIELD_NUMBER = 13;
    private java.lang.Object exchange_;
    public boolean hasExchange() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          exchange_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string accountId = 14;
    public static final int ACCOUNTID_FIELD_NUMBER = 14;
    private java.lang.Object accountId_;
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 validity = 15;
    public static final int VALIDITY_FIELD_NUMBER = 15;
    private int validity_;
    public boolean hasValidity() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public int getValidity() {
      return validity_;
    }
    
    // optional string validityDate = 16;
    public static final int VALIDITYDATE_FIELD_NUMBER = 16;
    private java.lang.Object validityDate_;
    public boolean hasValidityDate() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    public String getValidityDate() {
      java.lang.Object ref = validityDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          validityDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValidityDateBytes() {
      java.lang.Object ref = validityDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        validityDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string route = 17;
    public static final int ROUTE_FIELD_NUMBER = 17;
    private java.lang.Object route_;
    public boolean hasRoute() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    public String getRoute() {
      java.lang.Object ref = route_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          route_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string broker = 18;
    public static final int BROKER_FIELD_NUMBER = 18;
    private java.lang.Object broker_;
    public boolean hasBroker() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    public String getBroker() {
      java.lang.Object ref = broker_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          broker_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBrokerBytes() {
      java.lang.Object ref = broker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        broker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string portfolio = 19;
    public static final int PORTFOLIO_FIELD_NUMBER = 19;
    private java.lang.Object portfolio_;
    public boolean hasPortfolio() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    public String getPortfolio() {
      java.lang.Object ref = portfolio_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          portfolio_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPortfolioBytes() {
      java.lang.Object ref = portfolio_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        portfolio_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string securityId = 20;
    public static final int SECURITYID_FIELD_NUMBER = 20;
    private java.lang.Object securityId_;
    public boolean hasSecurityId() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    public String getSecurityId() {
      java.lang.Object ref = securityId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          securityId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSecurityIdBytes() {
      java.lang.Object ref = securityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        securityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string securityIdSource = 21;
    public static final int SECURITYIDSOURCE_FIELD_NUMBER = 21;
    private java.lang.Object securityIdSource_;
    public boolean hasSecurityIdSource() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    public String getSecurityIdSource() {
      java.lang.Object ref = securityIdSource_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          securityIdSource_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSecurityIdSourceBytes() {
      java.lang.Object ref = securityIdSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        securityIdSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string securityExchange = 22;
    public static final int SECURITYEXCHANGE_FIELD_NUMBER = 22;
    private java.lang.Object securityExchange_;
    public boolean hasSecurityExchange() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    public String getSecurityExchange() {
      java.lang.Object ref = securityExchange_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          securityExchange_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSecurityExchangeBytes() {
      java.lang.Object ref = securityExchange_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        securityExchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double lastPrice = 23;
    public static final int LASTPRICE_FIELD_NUMBER = 23;
    private double lastPrice_;
    public boolean hasLastPrice() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    public double getLastPrice() {
      return lastPrice_;
    }
    
    private void initFields() {
      reqType_ = 0;
      time_ = 0L;
      clientId_ = "";
      orderId_ = "";
      symbol_ = "";
      price_ = 0D;
      stoppx_ = 0D;
      side_ = 0;
      type_ = 0;
      quantity_ = 0L;
      minqty_ = 0L;
      openqty_ = 0L;
      exchange_ = "";
      accountId_ = "";
      validity_ = 0;
      validityDate_ = "";
      route_ = "";
      broker_ = "";
      portfolio_ = "";
      securityId_ = "";
      securityIdSource_ = "";
      securityExchange_ = "";
      lastPrice_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSymbol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSide()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExchange()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValidity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBroker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, reqType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSymbolBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, price_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, stoppx_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, side_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, type_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, quantity_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, minqty_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, openqty_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getExchangeBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, validity_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getValidityDateBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getRouteBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeBytes(18, getBrokerBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeBytes(19, getPortfolioBytes());
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeBytes(20, getSecurityIdBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeBytes(21, getSecurityIdSourceBytes());
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeBytes(22, getSecurityExchangeBytes());
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeDouble(23, lastPrice_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reqType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClientIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSymbolBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, price_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, stoppx_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, side_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, type_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, quantity_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, minqty_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, openqty_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getExchangeBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, validity_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getValidityDateBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getRouteBytes());
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getBrokerBytes());
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(19, getPortfolioBytes());
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getSecurityIdBytes());
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(21, getSecurityIdSourceBytes());
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(22, getSecurityExchangeBytes());
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(23, lastPrice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEOrderRequest.OrderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEOrderRequest.OrderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderRequest.OrderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEOrderRequest.OrderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderRequest.OrderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEOrderRequest.OrderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEOrderRequest.OrderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEOrderRequest.OrderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEOrderRequest.OrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEOrderRequest.OrderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEOrderRequest.OrderRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEOrderRequest.OrderRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEOrderRequest.internal_static_BE_OrderRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEOrderRequest.internal_static_BE_OrderRequest_fieldAccessorTable;
      }
      
      // Construct using BE.BEOrderRequest.OrderRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        reqType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        symbol_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        stoppx_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        side_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        quantity_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        minqty_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        openqty_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        exchange_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        accountId_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        validity_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        validityDate_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        route_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        broker_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        portfolio_ = "";
        bitField0_ = (bitField0_ & ~0x00040000);
        securityId_ = "";
        bitField0_ = (bitField0_ & ~0x00080000);
        securityIdSource_ = "";
        bitField0_ = (bitField0_ & ~0x00100000);
        securityExchange_ = "";
        bitField0_ = (bitField0_ & ~0x00200000);
        lastPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00400000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEOrderRequest.OrderRequest.getDescriptor();
      }
      
      public BE.BEOrderRequest.OrderRequest getDefaultInstanceForType() {
        return BE.BEOrderRequest.OrderRequest.getDefaultInstance();
      }
      
      public BE.BEOrderRequest.OrderRequest build() {
        BE.BEOrderRequest.OrderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEOrderRequest.OrderRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEOrderRequest.OrderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEOrderRequest.OrderRequest buildPartial() {
        BE.BEOrderRequest.OrderRequest result = new BE.BEOrderRequest.OrderRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.symbol_ = symbol_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.stoppx_ = stoppx_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.side_ = side_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.minqty_ = minqty_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.openqty_ = openqty_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.exchange_ = exchange_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.validity_ = validity_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.validityDate_ = validityDate_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.route_ = route_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.broker_ = broker_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.portfolio_ = portfolio_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.securityId_ = securityId_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.securityIdSource_ = securityIdSource_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.securityExchange_ = securityExchange_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.lastPrice_ = lastPrice_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEOrderRequest.OrderRequest) {
          return mergeFrom((BE.BEOrderRequest.OrderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEOrderRequest.OrderRequest other) {
        if (other == BE.BEOrderRequest.OrderRequest.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasSymbol()) {
          setSymbol(other.getSymbol());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasStoppx()) {
          setStoppx(other.getStoppx());
        }
        if (other.hasSide()) {
          setSide(other.getSide());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasMinqty()) {
          setMinqty(other.getMinqty());
        }
        if (other.hasOpenqty()) {
          setOpenqty(other.getOpenqty());
        }
        if (other.hasExchange()) {
          setExchange(other.getExchange());
        }
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasValidity()) {
          setValidity(other.getValidity());
        }
        if (other.hasValidityDate()) {
          setValidityDate(other.getValidityDate());
        }
        if (other.hasRoute()) {
          setRoute(other.getRoute());
        }
        if (other.hasBroker()) {
          setBroker(other.getBroker());
        }
        if (other.hasPortfolio()) {
          setPortfolio(other.getPortfolio());
        }
        if (other.hasSecurityId()) {
          setSecurityId(other.getSecurityId());
        }
        if (other.hasSecurityIdSource()) {
          setSecurityIdSource(other.getSecurityIdSource());
        }
        if (other.hasSecurityExchange()) {
          setSecurityExchange(other.getSecurityExchange());
        }
        if (other.hasLastPrice()) {
          setLastPrice(other.getLastPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasClientId()) {
          
          return false;
        }
        if (!hasOrderId()) {
          
          return false;
        }
        if (!hasSymbol()) {
          
          return false;
        }
        if (!hasSide()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasExchange()) {
          
          return false;
        }
        if (!hasAccountId()) {
          
          return false;
        }
        if (!hasValidity()) {
          
          return false;
        }
        if (!hasRoute()) {
          
          return false;
        }
        if (!hasBroker()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              reqType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              clientId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              orderId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              symbol_ = input.readBytes();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              price_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              stoppx_ = input.readDouble();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              side_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              type_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              quantity_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              minqty_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              openqty_ = input.readInt64();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              exchange_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              accountId_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              validity_ = input.readInt32();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              validityDate_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              route_ = input.readBytes();
              break;
            }
            case 146: {
              bitField0_ |= 0x00020000;
              broker_ = input.readBytes();
              break;
            }
            case 154: {
              bitField0_ |= 0x00040000;
              portfolio_ = input.readBytes();
              break;
            }
            case 162: {
              bitField0_ |= 0x00080000;
              securityId_ = input.readBytes();
              break;
            }
            case 170: {
              bitField0_ |= 0x00100000;
              securityIdSource_ = input.readBytes();
              break;
            }
            case 178: {
              bitField0_ |= 0x00200000;
              securityExchange_ = input.readBytes();
              break;
            }
            case 185: {
              bitField0_ |= 0x00400000;
              lastPrice_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 reqType = 1;
      private int reqType_ ;
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getReqType() {
        return reqType_;
      }
      public Builder setReqType(int value) {
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 time = 2;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // required string clientId = 3;
      private java.lang.Object clientId_ = "";
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClientId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clientId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      void setClientId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        clientId_ = value;
        onChanged();
      }
      
      // required string orderId = 4;
      private java.lang.Object orderId_ = "";
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOrderId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        orderId_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      void setOrderId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        orderId_ = value;
        onChanged();
      }
      
      // required string symbol = 5;
      private java.lang.Object symbol_ = "";
      public boolean hasSymbol() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSymbol(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        symbol_ = value;
        onChanged();
        return this;
      }
      public Builder clearSymbol() {
        bitField0_ = (bitField0_ & ~0x00000010);
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      void setSymbol(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        symbol_ = value;
        onChanged();
      }
      
      // optional double price = 6 [default = 0];
      private double price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getPrice() {
        return price_;
      }
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000020;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        price_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double stoppx = 7 [default = 0];
      private double stoppx_ ;
      public boolean hasStoppx() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public double getStoppx() {
        return stoppx_;
      }
      public Builder setStoppx(double value) {
        bitField0_ |= 0x00000040;
        stoppx_ = value;
        onChanged();
        return this;
      }
      public Builder clearStoppx() {
        bitField0_ = (bitField0_ & ~0x00000040);
        stoppx_ = 0D;
        onChanged();
        return this;
      }
      
      // required int32 side = 8;
      private int side_ ;
      public boolean hasSide() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getSide() {
        return side_;
      }
      public Builder setSide(int value) {
        bitField0_ |= 0x00000080;
        side_ = value;
        onChanged();
        return this;
      }
      public Builder clearSide() {
        bitField0_ = (bitField0_ & ~0x00000080);
        side_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 type = 9;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000100;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 quantity = 10 [default = 0];
      private long quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public long getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(long value) {
        bitField0_ |= 0x00000200;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000200);
        quantity_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 minqty = 11 [default = 0];
      private long minqty_ ;
      public boolean hasMinqty() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public long getMinqty() {
        return minqty_;
      }
      public Builder setMinqty(long value) {
        bitField0_ |= 0x00000400;
        minqty_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinqty() {
        bitField0_ = (bitField0_ & ~0x00000400);
        minqty_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 openqty = 12 [default = 0];
      private long openqty_ ;
      public boolean hasOpenqty() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public long getOpenqty() {
        return openqty_;
      }
      public Builder setOpenqty(long value) {
        bitField0_ |= 0x00000800;
        openqty_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpenqty() {
        bitField0_ = (bitField0_ & ~0x00000800);
        openqty_ = 0L;
        onChanged();
        return this;
      }
      
      // required string exchange = 13;
      private java.lang.Object exchange_ = "";
      public boolean hasExchange() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          exchange_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExchange(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        exchange_ = value;
        onChanged();
        return this;
      }
      public Builder clearExchange() {
        bitField0_ = (bitField0_ & ~0x00001000);
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      void setExchange(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        exchange_ = value;
        onChanged();
      }
      
      // required string accountId = 14;
      private java.lang.Object accountId_ = "";
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        accountId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00002000);
        accountId_ = getDefaultInstance().getAccountId();
        onChanged();
        return this;
      }
      void setAccountId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00002000;
        accountId_ = value;
        onChanged();
      }
      
      // required int32 validity = 15;
      private int validity_ ;
      public boolean hasValidity() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public int getValidity() {
        return validity_;
      }
      public Builder setValidity(int value) {
        bitField0_ |= 0x00004000;
        validity_ = value;
        onChanged();
        return this;
      }
      public Builder clearValidity() {
        bitField0_ = (bitField0_ & ~0x00004000);
        validity_ = 0;
        onChanged();
        return this;
      }
      
      // optional string validityDate = 16;
      private java.lang.Object validityDate_ = "";
      public boolean hasValidityDate() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      public String getValidityDate() {
        java.lang.Object ref = validityDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          validityDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValidityDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        validityDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearValidityDate() {
        bitField0_ = (bitField0_ & ~0x00008000);
        validityDate_ = getDefaultInstance().getValidityDate();
        onChanged();
        return this;
      }
      void setValidityDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00008000;
        validityDate_ = value;
        onChanged();
      }
      
      // required string route = 17;
      private java.lang.Object route_ = "";
      public boolean hasRoute() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      public String getRoute() {
        java.lang.Object ref = route_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          route_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRoute(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        route_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoute() {
        bitField0_ = (bitField0_ & ~0x00010000);
        route_ = getDefaultInstance().getRoute();
        onChanged();
        return this;
      }
      void setRoute(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00010000;
        route_ = value;
        onChanged();
      }
      
      // required string broker = 18;
      private java.lang.Object broker_ = "";
      public boolean hasBroker() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      public String getBroker() {
        java.lang.Object ref = broker_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          broker_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBroker(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        broker_ = value;
        onChanged();
        return this;
      }
      public Builder clearBroker() {
        bitField0_ = (bitField0_ & ~0x00020000);
        broker_ = getDefaultInstance().getBroker();
        onChanged();
        return this;
      }
      void setBroker(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00020000;
        broker_ = value;
        onChanged();
      }
      
      // optional string portfolio = 19;
      private java.lang.Object portfolio_ = "";
      public boolean hasPortfolio() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      public String getPortfolio() {
        java.lang.Object ref = portfolio_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          portfolio_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPortfolio(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00040000;
        portfolio_ = value;
        onChanged();
        return this;
      }
      public Builder clearPortfolio() {
        bitField0_ = (bitField0_ & ~0x00040000);
        portfolio_ = getDefaultInstance().getPortfolio();
        onChanged();
        return this;
      }
      void setPortfolio(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00040000;
        portfolio_ = value;
        onChanged();
      }
      
      // optional string securityId = 20;
      private java.lang.Object securityId_ = "";
      public boolean hasSecurityId() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      public String getSecurityId() {
        java.lang.Object ref = securityId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          securityId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSecurityId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
        securityId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSecurityId() {
        bitField0_ = (bitField0_ & ~0x00080000);
        securityId_ = getDefaultInstance().getSecurityId();
        onChanged();
        return this;
      }
      void setSecurityId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00080000;
        securityId_ = value;
        onChanged();
      }
      
      // optional string securityIdSource = 21;
      private java.lang.Object securityIdSource_ = "";
      public boolean hasSecurityIdSource() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      public String getSecurityIdSource() {
        java.lang.Object ref = securityIdSource_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          securityIdSource_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSecurityIdSource(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00100000;
        securityIdSource_ = value;
        onChanged();
        return this;
      }
      public Builder clearSecurityIdSource() {
        bitField0_ = (bitField0_ & ~0x00100000);
        securityIdSource_ = getDefaultInstance().getSecurityIdSource();
        onChanged();
        return this;
      }
      void setSecurityIdSource(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00100000;
        securityIdSource_ = value;
        onChanged();
      }
      
      // optional string securityExchange = 22;
      private java.lang.Object securityExchange_ = "";
      public boolean hasSecurityExchange() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      public String getSecurityExchange() {
        java.lang.Object ref = securityExchange_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          securityExchange_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSecurityExchange(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00200000;
        securityExchange_ = value;
        onChanged();
        return this;
      }
      public Builder clearSecurityExchange() {
        bitField0_ = (bitField0_ & ~0x00200000);
        securityExchange_ = getDefaultInstance().getSecurityExchange();
        onChanged();
        return this;
      }
      void setSecurityExchange(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00200000;
        securityExchange_ = value;
        onChanged();
      }
      
      // optional double lastPrice = 23;
      private double lastPrice_ ;
      public boolean hasLastPrice() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      public double getLastPrice() {
        return lastPrice_;
      }
      public Builder setLastPrice(double value) {
        bitField0_ |= 0x00400000;
        lastPrice_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastPrice() {
        bitField0_ = (bitField0_ & ~0x00400000);
        lastPrice_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BE.OrderRequest)
    }
    
    static {
      defaultInstance = new OrderRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.OrderRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_OrderRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_OrderRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protos/BE.OrderRequest.proto\022\002BE\"\267\003\n\014O" +
      "rderRequest\022\017\n\007reqType\030\001 \002(\005\022\014\n\004time\030\002 \002" +
      "(\003\022\020\n\010clientId\030\003 \002(\t\022\017\n\007orderId\030\004 \002(\t\022\016\n" +
      "\006symbol\030\005 \002(\t\022\020\n\005price\030\006 \001(\001:\0010\022\021\n\006stopp" +
      "x\030\007 \001(\001:\0010\022\014\n\004side\030\010 \002(\005\022\014\n\004type\030\t \002(\005\022\023" +
      "\n\010quantity\030\n \001(\003:\0010\022\021\n\006minqty\030\013 \001(\003:\0010\022\022" +
      "\n\007openqty\030\014 \001(\003:\0010\022\020\n\010exchange\030\r \002(\t\022\021\n\t" +
      "accountId\030\016 \002(\t\022\020\n\010validity\030\017 \002(\005\022\024\n\014val" +
      "idityDate\030\020 \001(\t\022\r\n\005route\030\021 \002(\t\022\016\n\006broker" +
      "\030\022 \002(\t\022\021\n\tportfolio\030\023 \001(\t\022\022\n\nsecurityId\030",
      "\024 \001(\t\022\030\n\020securityIdSource\030\025 \001(\t\022\030\n\020secur" +
      "ityExchange\030\026 \001(\t\022\021\n\tlastPrice\030\027 \001(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BE_OrderRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BE_OrderRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_OrderRequest_descriptor,
              new java.lang.String[] { "ReqType", "Time", "ClientId", "OrderId", "Symbol", "Price", "Stoppx", "Side", "Type", "Quantity", "Minqty", "Openqty", "Exchange", "AccountId", "Validity", "ValidityDate", "Route", "Broker", "Portfolio", "SecurityId", "SecurityIdSource", "SecurityExchange", "LastPrice", },
              BE.BEOrderRequest.OrderRequest.class,
              BE.BEOrderRequest.OrderRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
