// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BE.PositionRequest.proto

package BE;

public final class BEPositionRequest {
  private BEPositionRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PositionRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string client = 1;
    boolean hasClient();
    String getClient();
    
    // optional string exchange = 2;
    boolean hasExchange();
    String getExchange();
    
    // optional string security = 3;
    boolean hasSecurity();
    String getSecurity();
  }
  public static final class PositionRequest extends
      com.google.protobuf.GeneratedMessage
      implements PositionRequestOrBuilder {
    // Use PositionRequest.newBuilder() to construct.
    private PositionRequest(Builder builder) {
      super(builder);
    }
    private PositionRequest(boolean noInit) {}
    
    private static final PositionRequest defaultInstance;
    public static PositionRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PositionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BE.BEPositionRequest.internal_static_BE_PositionRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BE.BEPositionRequest.internal_static_BE_PositionRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string client = 1;
    public static final int CLIENT_FIELD_NUMBER = 1;
    private java.lang.Object client_;
    public boolean hasClient() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getClient() {
      java.lang.Object ref = client_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          client_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientBytes() {
      java.lang.Object ref = client_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        client_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string exchange = 2;
    public static final int EXCHANGE_FIELD_NUMBER = 2;
    private java.lang.Object exchange_;
    public boolean hasExchange() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          exchange_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string security = 3;
    public static final int SECURITY_FIELD_NUMBER = 3;
    private java.lang.Object security_;
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getSecurity() {
      java.lang.Object ref = security_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          security_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSecurityBytes() {
      java.lang.Object ref = security_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        security_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      client_ = "";
      exchange_ = "";
      security_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasClient()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClientBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getExchangeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSecurityBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClientBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getExchangeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSecurityBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static BE.BEPositionRequest.PositionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEPositionRequest.PositionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEPositionRequest.PositionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static BE.BEPositionRequest.PositionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEPositionRequest.PositionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEPositionRequest.PositionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static BE.BEPositionRequest.PositionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEPositionRequest.PositionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static BE.BEPositionRequest.PositionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static BE.BEPositionRequest.PositionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BE.BEPositionRequest.PositionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BE.BEPositionRequest.PositionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BE.BEPositionRequest.internal_static_BE_PositionRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BE.BEPositionRequest.internal_static_BE_PositionRequest_fieldAccessorTable;
      }
      
      // Construct using BE.BEPositionRequest.PositionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        client_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        exchange_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        security_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BE.BEPositionRequest.PositionRequest.getDescriptor();
      }
      
      public BE.BEPositionRequest.PositionRequest getDefaultInstanceForType() {
        return BE.BEPositionRequest.PositionRequest.getDefaultInstance();
      }
      
      public BE.BEPositionRequest.PositionRequest build() {
        BE.BEPositionRequest.PositionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private BE.BEPositionRequest.PositionRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        BE.BEPositionRequest.PositionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public BE.BEPositionRequest.PositionRequest buildPartial() {
        BE.BEPositionRequest.PositionRequest result = new BE.BEPositionRequest.PositionRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.client_ = client_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.exchange_ = exchange_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.security_ = security_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BE.BEPositionRequest.PositionRequest) {
          return mergeFrom((BE.BEPositionRequest.PositionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(BE.BEPositionRequest.PositionRequest other) {
        if (other == BE.BEPositionRequest.PositionRequest.getDefaultInstance()) return this;
        if (other.hasClient()) {
          setClient(other.getClient());
        }
        if (other.hasExchange()) {
          setExchange(other.getExchange());
        }
        if (other.hasSecurity()) {
          setSecurity(other.getSecurity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasClient()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              client_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              exchange_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              security_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string client = 1;
      private java.lang.Object client_ = "";
      public boolean hasClient() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getClient() {
        java.lang.Object ref = client_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          client_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClient(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        client_ = value;
        onChanged();
        return this;
      }
      public Builder clearClient() {
        bitField0_ = (bitField0_ & ~0x00000001);
        client_ = getDefaultInstance().getClient();
        onChanged();
        return this;
      }
      void setClient(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        client_ = value;
        onChanged();
      }
      
      // optional string exchange = 2;
      private java.lang.Object exchange_ = "";
      public boolean hasExchange() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          exchange_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExchange(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exchange_ = value;
        onChanged();
        return this;
      }
      public Builder clearExchange() {
        bitField0_ = (bitField0_ & ~0x00000002);
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      void setExchange(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        exchange_ = value;
        onChanged();
      }
      
      // optional string security = 3;
      private java.lang.Object security_ = "";
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getSecurity() {
        java.lang.Object ref = security_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          security_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSecurity(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        security_ = value;
        onChanged();
        return this;
      }
      public Builder clearSecurity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        security_ = getDefaultInstance().getSecurity();
        onChanged();
        return this;
      }
      void setSecurity(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        security_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:BE.PositionRequest)
    }
    
    static {
      defaultInstance = new PositionRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BE.PositionRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BE_PositionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BE_PositionRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037protos/BE.PositionRequest.proto\022\002BE\"E\n" +
      "\017PositionRequest\022\016\n\006client\030\001 \002(\t\022\020\n\010exch" +
      "ange\030\002 \001(\t\022\020\n\010security\030\003 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BE_PositionRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BE_PositionRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BE_PositionRequest_descriptor,
              new java.lang.String[] { "Client", "Exchange", "Security", },
              BE.BEPositionRequest.PositionRequest.class,
              BE.BEPositionRequest.PositionRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
